{
    "acts": [
        "ACT.OVERGROWTH",
        "ACT.HIVE",
        "ACT.GLORY"
    ],
    "ascension": 7,
    "build_id": "v0.98.3",
    "game_mode": "standard",
    "killed_by_encounter": "NONE.NONE",
    "killed_by_event": "NONE.NONE",
    "map_point_history": [
        [
            {
                "map_point_type": "ancient",
                "player_stats": [
                    {
                        "ancient_choice": [
                            {
                                "TextKey": "NUTRITIOUS_OYSTER",
                                "title": {
                                    "key": "NUTRITIOUS_OYSTER.title",
                                    "table": "relics"
                                },
                                "was_chosen": false
                            },
                            {
                                "TextKey": "NEW_LEAF",
                                "title": {
                                    "key": "NEW_LEAF.title",
                                    "table": "relics"
                                },
                                "was_chosen": false
                            },
                            {
                                "TextKey": "PRECARIOUS_SHEARS",
                                "title": {
                                    "key": "PRECARIOUS_SHEARS.title",
                                    "table": "relics"
                                },
                                "was_chosen": true
                            }
                        ],
                        "cards_removed": [
                            {
                                "floor_added_to_deck": 1,
                                "id": "CARD.STRIKE_NECROBINDER"
                            },
                            {
                                "floor_added_to_deck": 1,
                                "id": "CARD.STRIKE_NECROBINDER"
                            }
                        ],
                        "current_gold": 99,
                        "current_hp": 39,
                        "damage_taken": 13,
                        "event_choices": [
                            {
                                "title": {
                                    "key": "PRECARIOUS_SHEARS.title",
                                    "table": "relics"
                                }
                            }
                        ],
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 52,
                        "max_hp": 66,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "relic_choices": [
                            {
                                "choice": "RELIC.PRECARIOUS_SHEARS",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "EVENT.NEOW",
                        "room_type": "event",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 2,
                                    "id": "CARD.COUNTDOWN"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.NO_ESCAPE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.PULL_AGGRO"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.COUNTDOWN"
                            }
                        ],
                        "current_gold": 110,
                        "current_hp": 39,
                        "damage_taken": 0,
                        "gold_gained": 11,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 66,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.NIBBITS_WEAK",
                        "monster_ids": [
                            "MONSTER.NIBBIT"
                        ],
                        "room_type": "monster",
                        "turns_taken": 5
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 3,
                                    "id": "CARD.DEATHS_DOOR"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.INVOKE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.BORROWED_TIME"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.DEATHS_DOOR"
                            }
                        ],
                        "current_gold": 124,
                        "current_hp": 39,
                        "damage_taken": 0,
                        "gold_gained": 14,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 66,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.SLIMES_WEAK",
                        "monster_ids": [
                            "MONSTER.LEAF_SLIME_S",
                            "MONSTER.LEAF_SLIME_M",
                            "MONSTER.TWIG_SLIME_S"
                        ],
                        "room_type": "monster",
                        "turns_taken": 5
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 4,
                                    "id": "CARD.ENFEEBLING_TOUCH"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.BLIGHT_STRIKE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.BONE_SHARDS"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.ENFEEBLING_TOUCH"
                            }
                        ],
                        "current_gold": 136,
                        "current_hp": 39,
                        "damage_taken": 0,
                        "gold_gained": 12,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 66,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.FUZZY_WURM_CRAWLER_WEAK",
                        "monster_ids": [
                            "MONSTER.FUZZY_WURM_CRAWLER"
                        ],
                        "room_type": "monster",
                        "turns_taken": 5
                    }
                ]
            },
            {
                "map_point_type": "unknown",
                "player_stats": [
                    {
                        "cards_enchanted": [
                            {
                                "card": {
                                    "enchantment": {
                                        "amount": 2,
                                        "id": "ENCHANTMENT.NIMBLE"
                                    },
                                    "floor_added_to_deck": 3,
                                    "id": "CARD.DEATHS_DOOR"
                                },
                                "enchantment": "ENCHANTMENT.NIMBLE"
                            }
                        ],
                        "current_gold": 136,
                        "current_hp": 39,
                        "damage_taken": 0,
                        "event_choices": [
                            {
                                "title": {
                                    "key": "SELF_HELP_BOOK.pages.INITIAL.options.READ_PASSAGE.title",
                                    "table": "events"
                                },
                                "variables": {
                                    "Enchantment1": {
                                        "type": "DynamicString",
                                        "decimal_value": 0,
                                        "bool_value": false,
                                        "string_value": "Sharp"
                                    },
                                    "Enchantment2": {
                                        "type": "DynamicString",
                                        "decimal_value": 0,
                                        "bool_value": false,
                                        "string_value": "Nimble"
                                    },
                                    "Enchantment3": {
                                        "type": "DynamicString",
                                        "decimal_value": 0,
                                        "bool_value": false,
                                        "string_value": "Swift"
                                    }
                                }
                            }
                        ],
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 66,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "EVENT.SELF_HELP_BOOK",
                        "room_type": "event",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "elite",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 6,
                                    "id": "CARD.LETHALITY"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.VEILPIERCER"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.FEAR"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.LETHALITY"
                            }
                        ],
                        "current_gold": 162,
                        "current_hp": 13,
                        "damage_taken": 26,
                        "gold_gained": 26,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 66,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.SWIFT_POTION",
                                "was_picked": true
                            }
                        ],
                        "relic_choices": [
                            {
                                "choice": "RELIC.REPTILE_TRINKET",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.BYRDONIS_ELITE",
                        "monster_ids": [
                            "MONSTER.BYRDONIS"
                        ],
                        "room_type": "elite",
                        "turns_taken": 9
                    }
                ]
            },
            {
                "map_point_type": "rest_site",
                "player_stats": [
                    {
                        "current_gold": 162,
                        "current_hp": 32,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 19,
                        "max_hp": 66,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "rest_site_choices": [
                            "HEAL"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "rest_site",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "unknown",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 8,
                                    "id": "CARD.GRAVE_WARDEN"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.DELAY"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.DANSE_MACABRE"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.GRAVE_WARDEN"
                            }
                        ],
                        "current_gold": 171,
                        "current_hp": 30,
                        "damage_taken": 2,
                        "gold_gained": 9,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 66,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.ATTACK_POTION",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.MAWLER_NORMAL",
                        "monster_ids": [
                            "MONSTER.MAWLER"
                        ],
                        "room_type": "monster",
                        "turns_taken": 5
                    }
                ]
            },
            {
                "map_point_type": "elite",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 9,
                                    "id": "CARD.NEGATIVE_PULSE"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.DEATHBRINGER"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.WISP"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.NEGATIVE_PULSE"
                            }
                        ],
                        "current_gold": 199,
                        "current_hp": 29,
                        "damage_taken": 1,
                        "gold_gained": 28,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 66,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.POWER_POTION",
                                "was_picked": true
                            }
                        ],
                        "potion_used": [
                            "POTION.ATTACK_POTION",
                            "POTION.SWIFT_POTION"
                        ],
                        "relic_choices": [
                            {
                                "choice": "RELIC.BIG_HAT",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.PHROG_PARASITE_ELITE",
                        "monster_ids": [
                            "MONSTER.PHROG_PARASITE"
                        ],
                        "room_type": "elite",
                        "turns_taken": 8
                    }
                ]
            },
            {
                "map_point_type": "treasure",
                "player_stats": [
                    {
                        "current_gold": 235,
                        "current_hp": 29,
                        "damage_taken": 0,
                        "gold_gained": 36,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 66,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "relic_choices": [
                            {
                                "choice": "RELIC.FESTIVE_POPPER",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "treasure",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "unknown",
                "player_stats": [
                    {
                        "cards_transformed": [
                            {
                                "final_card": {
                                    "floor_added_to_deck": 11,
                                    "id": "CARD.PAGESTORM"
                                },
                                "original_card": {
                                    "floor_added_to_deck": 1,
                                    "id": "CARD.STRIKE_NECROBINDER"
                                }
                            },
                            {
                                "final_card": {
                                    "floor_added_to_deck": 11,
                                    "id": "CARD.NO_ESCAPE"
                                },
                                "original_card": {
                                    "floor_added_to_deck": 1,
                                    "id": "CARD.STRIKE_NECROBINDER"
                                }
                            }
                        ],
                        "current_gold": 135,
                        "current_hp": 29,
                        "damage_taken": 0,
                        "event_choices": [
                            {
                                "title": {
                                    "key": "MORPHIC_GROVE.pages.INITIAL.options.GROUP.title",
                                    "table": "events"
                                }
                            }
                        ],
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 100,
                        "hp_healed": 0,
                        "max_hp": 66,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "EVENT.MORPHIC_GROVE",
                        "room_type": "event",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "rest_site",
                "player_stats": [
                    {
                        "current_gold": 135,
                        "current_hp": 48,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 19,
                        "max_hp": 66,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "rest_site_choices": [
                            "HEAL"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "rest_site",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "id": "CARD.AFTERLIFE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.DRAIN_POWER"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.BONE_SHARDS"
                                },
                                "was_picked": false
                            }
                        ],
                        "current_gold": 144,
                        "current_hp": 40,
                        "damage_taken": 8,
                        "gold_gained": 9,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 66,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.SLITHERING_STRANGLER_NORMAL",
                        "monster_ids": [
                            "MONSTER.LEAF_SLIME_M",
                            "MONSTER.SLITHERING_STRANGLER"
                        ],
                        "room_type": "monster",
                        "turns_taken": 5
                    }
                ]
            },
            {
                "map_point_type": "elite",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 14,
                                    "id": "CARD.DIRGE"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.BONE_SHARDS"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.GRAVE_WARDEN"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.DIRGE"
                            }
                        ],
                        "current_gold": 176,
                        "current_hp": 47,
                        "damage_taken": 0,
                        "gold_gained": 32,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 7,
                        "max_hp": 73,
                        "max_hp_gained": 7,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.SWIFT_POTION",
                                "was_picked": true
                            }
                        ],
                        "potion_used": [
                            "POTION.POWER_POTION"
                        ],
                        "relic_choices": [
                            {
                                "choice": "RELIC.STRAWBERRY",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.BYGONE_EFFIGY_ELITE",
                        "monster_ids": [
                            "MONSTER.BYGONE_EFFIGY"
                        ],
                        "room_type": "elite",
                        "turns_taken": 6
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 15,
                                    "id": "CARD.FRIENDSHIP"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.PULL_FROM_BELOW"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.RATTLE"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.FRIENDSHIP"
                            }
                        ],
                        "current_gold": 187,
                        "current_hp": 47,
                        "damage_taken": 0,
                        "gold_gained": 11,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.SLIMES_NORMAL",
                        "monster_ids": [
                            "MONSTER.TWIG_SLIME_M",
                            "MONSTER.LEAF_SLIME_M",
                            "MONSTER.TWIG_SLIME_S",
                            "MONSTER.LEAF_SLIME_S"
                        ],
                        "room_type": "monster",
                        "turns_taken": 4
                    }
                ]
            },
            {
                "map_point_type": "rest_site",
                "player_stats": [
                    {
                        "current_gold": 187,
                        "current_hp": 47,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "rest_site_choices": [
                            "SMITH"
                        ],
                        "upgraded_cards": [
                            "CARD.NO_ESCAPE"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "rest_site",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "boss",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 17,
                                    "id": "CARD.NEUROSURGE"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.SACRIFICE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.SENTRY_MODE"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.NEUROSURGE"
                            }
                        ],
                        "current_gold": 262,
                        "current_hp": 26,
                        "damage_taken": 21,
                        "gold_gained": 75,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.CLARITY",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.THE_KIN_BOSS",
                        "monster_ids": [
                            "MONSTER.KIN_FOLLOWER",
                            "MONSTER.KIN_FOLLOWER",
                            "MONSTER.KIN_PRIEST"
                        ],
                        "room_type": "boss",
                        "turns_taken": 9
                    }
                ]
            }
        ],
        [
            {
                "map_point_type": "ancient",
                "player_stats": [
                    {
                        "ancient_choice": [
                            {
                                "TextKey": "PRISMATIC_GEM",
                                "title": {
                                    "key": "PRISMATIC_GEM.title",
                                    "table": "relics"
                                },
                                "was_chosen": false
                            },
                            {
                                "TextKey": "RADIANT_PEARL",
                                "title": {
                                    "key": "RADIANT_PEARL.title",
                                    "table": "relics"
                                },
                                "was_chosen": false
                            },
                            {
                                "TextKey": "TOUCH_OF_OROBAS",
                                "title": {
                                    "key": "TOUCH_OF_OROBAS.title",
                                    "table": "relics"
                                },
                                "was_chosen": true
                            }
                        ],
                        "current_gold": 262,
                        "current_hp": 63,
                        "damage_taken": 0,
                        "event_choices": [
                            {
                                "title": {
                                    "key": "TOUCH_OF_OROBAS.title",
                                    "table": "relics"
                                }
                            }
                        ],
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 37,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "relic_choices": [
                            {
                                "choice": "RELIC.TOUCH_OF_OROBAS",
                                "was_picked": true
                            },
                            {
                                "choice": "RELIC.PHYLACTERY_UNBOUND",
                                "was_picked": true
                            }
                        ],
                        "relics_removed": [
                            "RELIC.BOUND_PHYLACTERY"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "EVENT.OROBAS",
                        "room_type": "event",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "floor_added_to_deck": 19,
                                    "id": "CARD.BORROWED_TIME"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.INVOKE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.REAVE"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "current_upgrade_level": 1,
                                "id": "CARD.BORROWED_TIME"
                            }
                        ],
                        "current_gold": 272,
                        "current_hp": 63,
                        "damage_taken": 0,
                        "gold_gained": 10,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.SHIP_IN_A_BOTTLE",
                                "was_picked": false
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.EXOSKELETONS_WEAK",
                        "monster_ids": [
                            "MONSTER.EXOSKELETON",
                            "MONSTER.EXOSKELETON",
                            "MONSTER.EXOSKELETON"
                        ],
                        "room_type": "monster",
                        "turns_taken": 4
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 20,
                                    "id": "CARD.GRAVE_WARDEN"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.BLIGHT_STRIKE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.FEAR"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.GRAVE_WARDEN"
                            }
                        ],
                        "current_gold": 284,
                        "current_hp": 63,
                        "damage_taken": 0,
                        "gold_gained": 12,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.COLORLESS_POTION",
                                "was_picked": false
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.BOWLBUGS_WEAK",
                        "monster_ids": [
                            "MONSTER.BOWLBUG_ROCK",
                            "MONSTER.BOWLBUG_NECTAR"
                        ],
                        "room_type": "monster",
                        "turns_taken": 3
                    }
                ]
            },
            {
                "map_point_type": "shop",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "id": "CARD.REAVE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.FLATTEN"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.WISP"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.LETHALITY"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.PANACHE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.BOLAS"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.DEFY"
                            }
                        ],
                        "cards_removed": [
                            {
                                "floor_added_to_deck": 1,
                                "id": "CARD.DEFEND_NECROBINDER"
                            }
                        ],
                        "current_gold": 159,
                        "current_hp": 63,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 125,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.SPEED_POTION",
                                "was_picked": false
                            },
                            {
                                "choice": "POTION.TOUCH_OF_INSANITY",
                                "was_picked": false
                            },
                            {
                                "choice": "POTION.POTION_OF_DOOM",
                                "was_picked": false
                            }
                        ],
                        "relic_choices": [
                            {
                                "choice": "RELIC.CENTENNIAL_PUZZLE",
                                "was_picked": false
                            },
                            {
                                "choice": "RELIC.MOLTEN_EGG",
                                "was_picked": false
                            },
                            {
                                "choice": "RELIC.PUNCH_DAGGER",
                                "was_picked": false
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "shop",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "id": "CARD.CALCIFY"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.RATTLE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.SCOURGE"
                                },
                                "was_picked": false
                            }
                        ],
                        "current_gold": 166,
                        "current_hp": 63,
                        "damage_taken": 0,
                        "gold_gained": 7,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.EXPLOSIVE_AMPOULE",
                                "was_picked": false
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.EXOSKELETONS_NORMAL",
                        "monster_ids": [
                            "MONSTER.EXOSKELETON",
                            "MONSTER.EXOSKELETON",
                            "MONSTER.EXOSKELETON",
                            "MONSTER.EXOSKELETON"
                        ],
                        "room_type": "monster",
                        "turns_taken": 4
                    }
                ]
            },
            {
                "map_point_type": "elite",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 23,
                                    "id": "CARD.BANSHEES_CRY"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.DIRGE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.DEFILE"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.BANSHEES_CRY"
                            }
                        ],
                        "current_gold": 195,
                        "current_hp": 48,
                        "damage_taken": 15,
                        "gold_gained": 29,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "relic_choices": [
                            {
                                "choice": "RELIC.VAJRA",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.INFESTED_PRISMS_ELITE",
                        "monster_ids": [
                            "MONSTER.INFESTED_PRISM"
                        ],
                        "room_type": "elite",
                        "turns_taken": 7
                    }
                ]
            },
            {
                "map_point_type": "rest_site",
                "player_stats": [
                    {
                        "current_gold": 195,
                        "current_hp": 48,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "rest_site_choices": [
                            "SMITH"
                        ],
                        "upgraded_cards": [
                            "CARD.PAGESTORM"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "rest_site",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "unknown",
                "player_stats": [
                    {
                        "cards_gained": [
                            {
                                "id": "CARD.DANSE_MACABRE"
                            }
                        ],
                        "current_gold": 195,
                        "current_hp": 48,
                        "damage_taken": 0,
                        "event_choices": [
                            {
                                "title": {
                                    "key": "INFESTED_AUTOMATON.pages.INITIAL.options.STUDY.title",
                                    "table": "events"
                                }
                            }
                        ],
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "EVENT.INFESTED_AUTOMATON",
                        "room_type": "event",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "treasure",
                "player_stats": [
                    {
                        "current_gold": 228,
                        "current_hp": 48,
                        "damage_taken": 0,
                        "gold_gained": 33,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "relic_choices": [
                            {
                                "choice": "RELIC.HAPPY_FLOWER",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "treasure",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 27,
                                    "id": "CARD.NEGATIVE_PULSE"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.FLATTEN"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.REAP"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.NEGATIVE_PULSE"
                            }
                        ],
                        "current_gold": 235,
                        "current_hp": 48,
                        "damage_taken": 0,
                        "gold_gained": 7,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.MYTES_NORMAL",
                        "monster_ids": [
                            "MONSTER.MYTE",
                            "MONSTER.MYTE"
                        ],
                        "room_type": "monster",
                        "turns_taken": 3
                    }
                ]
            },
            {
                "map_point_type": "rest_site",
                "player_stats": [
                    {
                        "current_gold": 235,
                        "current_hp": 48,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "rest_site_choices": [
                            "SMITH"
                        ],
                        "upgraded_cards": [
                            "CARD.DEFY"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "rest_site",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "elite",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "id": "CARD.SEVERANCE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.DEFILE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.CALCIFY"
                                },
                                "was_picked": false
                            }
                        ],
                        "current_gold": 265,
                        "current_hp": 48,
                        "damage_taken": 0,
                        "gold_gained": 30,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.EXPLOSIVE_AMPOULE",
                                "was_picked": false
                            }
                        ],
                        "relic_choices": [
                            {
                                "choice": "RELIC.BONE_FLUTE",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.ENTOMANCER_ELITE",
                        "monster_ids": [
                            "MONSTER.ENTOMANCER"
                        ],
                        "room_type": "elite",
                        "turns_taken": 5
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "floor_added_to_deck": 30,
                                    "id": "CARD.SCOURGE"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.BORROWED_TIME"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.SNAP"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "current_upgrade_level": 1,
                                "id": "CARD.SCOURGE"
                            }
                        ],
                        "current_gold": 274,
                        "current_hp": 48,
                        "damage_taken": 0,
                        "gold_gained": 9,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.BONE_BREW",
                                "was_picked": false
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.HUNTER_KILLER_NORMAL",
                        "monster_ids": [
                            "MONSTER.HUNTER_KILLER"
                        ],
                        "room_type": "monster",
                        "turns_taken": 3
                    }
                ]
            },
            {
                "map_point_type": "elite",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 31,
                                    "id": "CARD.SEANCE"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.SOW"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.WISP"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.SEANCE"
                            }
                        ],
                        "current_gold": 302,
                        "current_hp": 48,
                        "damage_taken": 0,
                        "gold_gained": 28,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "relic_choices": [
                            {
                                "choice": "RELIC.ART_OF_WAR",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.DECIMILLIPEDE_ELITE",
                        "monster_ids": [
                            "MONSTER.DECIMILLIPEDE_SEGMENT_FRONT",
                            "MONSTER.DECIMILLIPEDE_SEGMENT_MIDDLE",
                            "MONSTER.DECIMILLIPEDE_SEGMENT_BACK"
                        ],
                        "room_type": "elite",
                        "turns_taken": 4
                    }
                ]
            },
            {
                "map_point_type": "rest_site",
                "player_stats": [
                    {
                        "current_gold": 302,
                        "current_hp": 48,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "rest_site_choices": [
                            "SMITH"
                        ],
                        "upgraded_cards": [
                            "CARD.LETHALITY"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "rest_site",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "boss",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 33,
                                    "id": "CARD.DEMESNE"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.UNDEATH"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.SQUEEZE"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.DEMESNE"
                            }
                        ],
                        "current_gold": 377,
                        "current_hp": 48,
                        "damage_taken": 0,
                        "gold_gained": 75,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.KNOWLEDGE_DEMON_BOSS",
                        "monster_ids": [
                            "MONSTER.KNOWLEDGE_DEMON"
                        ],
                        "room_type": "boss",
                        "turns_taken": 5
                    }
                ]
            }
        ],
        [
            {
                "map_point_type": "ancient",
                "player_stats": [
                    {
                        "ancient_choice": [
                            {
                                "TextKey": "WHISPERING_EARRING",
                                "title": {
                                    "key": "WHISPERING_EARRING.title",
                                    "table": "relics"
                                },
                                "was_chosen": false
                            },
                            {
                                "TextKey": "SERE_TALON",
                                "title": {
                                    "key": "SERE_TALON.title",
                                    "table": "relics"
                                },
                                "was_chosen": false
                            },
                            {
                                "TextKey": "JEWELED_MASK",
                                "title": {
                                    "key": "JEWELED_MASK.title",
                                    "table": "relics"
                                },
                                "was_chosen": true
                            }
                        ],
                        "current_gold": 377,
                        "current_hp": 68,
                        "damage_taken": 0,
                        "event_choices": [
                            {
                                "title": {
                                    "key": "JEWELED_MASK.title",
                                    "table": "relics"
                                }
                            }
                        ],
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 20,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "relic_choices": [
                            {
                                "choice": "RELIC.JEWELED_MASK",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "EVENT.VAKUU",
                        "room_type": "event",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 35,
                                    "id": "CARD.PARSE"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.DEATHBRINGER"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.DRAIN_POWER"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.PARSE"
                            }
                        ],
                        "current_gold": 391,
                        "current_hp": 68,
                        "damage_taken": 0,
                        "gold_gained": 14,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.FIRE_POTION",
                                "was_picked": false
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.TURRET_OPERATOR_WEAK",
                        "monster_ids": [
                            "MONSTER.LIVING_SHIELD",
                            "MONSTER.TURRET_OPERATOR"
                        ],
                        "room_type": "monster",
                        "turns_taken": 1
                    }
                ]
            },
            {
                "map_point_type": "unknown",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 36,
                                    "id": "CARD.SEANCE"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.SHARED_FATE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.REAPER_FORM"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.DOUBT"
                            },
                            {
                                "id": "CARD.SEANCE"
                            }
                        ],
                        "current_gold": 361,
                        "current_hp": 68,
                        "damage_taken": 0,
                        "event_choices": [
                            {
                                "title": {
                                    "key": "CRYSTAL_SPHERE.pages.INITIAL.options.UNCOVER_FUTURE.title",
                                    "table": "events"
                                },
                                "variables": {
                                    "UncoverFutureCost": {
                                        "type": "BaseDynamic",
                                        "decimal_value": 60,
                                        "bool_value": false,
                                        "string_value": null
                                    },
                                    "UncoverFutureProphesizeCount": {
                                        "type": "BaseDynamic",
                                        "decimal_value": 3,
                                        "bool_value": false,
                                        "string_value": null
                                    },
                                    "PaymentPlanCount": {
                                        "type": "BaseDynamic",
                                        "decimal_value": 6,
                                        "bool_value": false,
                                        "string_value": null
                                    },
                                    "CurseTitle": {
                                        "type": "DynamicString",
                                        "decimal_value": 0,
                                        "bool_value": false,
                                        "string_value": "Debt"
                                    }
                                }
                            }
                        ],
                        "gold_gained": 30,
                        "gold_lost": 0,
                        "gold_spent": 60,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.DISTILLED_CHAOS",
                                "was_picked": false
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "EVENT.CRYSTAL_SPHERE",
                        "room_type": "event",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "id": "CARD.POKE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "id": "CARD.LETHALITY"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.GRAVEBLAST"
                                },
                                "was_picked": false
                            }
                        ],
                        "current_gold": 373,
                        "current_hp": 68,
                        "damage_taken": 0,
                        "gold_gained": 12,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.COLORLESS_POTION",
                                "was_picked": false
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.DEVOTED_SCULPTOR_WEAK",
                        "monster_ids": [
                            "MONSTER.DEVOTED_SCULPTOR"
                        ],
                        "room_type": "monster",
                        "turns_taken": 3
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "floor_added_to_deck": 38,
                                    "id": "CARD.SCOURGE"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.REAP"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "id": "CARD.REAVE"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "current_upgrade_level": 1,
                                "id": "CARD.SCOURGE"
                            }
                        ],
                        "current_gold": 387,
                        "current_hp": 68,
                        "damage_taken": 0,
                        "gold_gained": 14,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_used": [
                            "POTION.SWIFT_POTION"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.THE_LOST_AND_FORGOTTEN_NORMAL",
                        "monster_ids": [
                            "MONSTER.THE_LOST",
                            "MONSTER.THE_FORGOTTEN"
                        ],
                        "room_type": "monster",
                        "turns_taken": 3
                    }
                ]
            },
            {
                "map_point_type": "shop",
                "player_stats": [
                    {
                        "bought_relics": [
                            "RELIC.BAG_OF_PREPARATION"
                        ],
                        "card_choices": [
                            {
                                "card": {
                                    "id": "CARD.HIGH_FIVE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.RATTLE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.WISP"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.GRAVE_WARDEN"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.FINESSE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.ETERNAL_ARMOR"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.PAGESTORM"
                            }
                        ],
                        "cards_removed": [
                            {
                                "floor_added_to_deck": 36,
                                "id": "CARD.DOUBT"
                            }
                        ],
                        "current_gold": 24,
                        "current_hp": 68,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 363,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.SWIFT_POTION",
                                "was_picked": false
                            },
                            {
                                "choice": "POTION.SPEED_POTION",
                                "was_picked": false
                            },
                            {
                                "choice": "POTION.SKILL_POTION",
                                "was_picked": false
                            }
                        ],
                        "relic_choices": [
                            {
                                "choice": "RELIC.BAG_OF_PREPARATION",
                                "was_picked": true
                            },
                            {
                                "choice": "RELIC.BOOK_REPAIR_KNIFE",
                                "was_picked": false
                            },
                            {
                                "choice": "RELIC.GNARLED_HAMMER",
                                "was_picked": false
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "shop",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "rest_site",
                "player_stats": [
                    {
                        "current_gold": 24,
                        "current_hp": 68,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "rest_site_choices": [
                            "SMITH"
                        ],
                        "upgraded_cards": [
                            "CARD.DEMESNE"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "rest_site",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "treasure",
                "player_stats": [
                    {
                        "current_gold": 60,
                        "current_hp": 68,
                        "damage_taken": 0,
                        "gold_gained": 36,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "relic_choices": [
                            {
                                "choice": "RELIC.GREMLIN_HORN",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "treasure",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "elite",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "id": "CARD.SCOURGE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "id": "CARD.BONE_SHARDS"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.SNAP"
                                },
                                "was_picked": false
                            }
                        ],
                        "current_gold": 93,
                        "current_hp": 64,
                        "damage_taken": 4,
                        "gold_gained": 33,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "relic_choices": [
                            {
                                "choice": "RELIC.GORGET",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.SOUL_NEXUS_ELITE",
                        "monster_ids": [
                            "MONSTER.SOUL_NEXUS"
                        ],
                        "room_type": "elite",
                        "turns_taken": 4
                    }
                ]
            },
            {
                "map_point_type": "rest_site",
                "player_stats": [
                    {
                        "current_gold": 93,
                        "current_hp": 64,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "rest_site_choices": [
                            "SMITH"
                        ],
                        "upgraded_cards": [
                            "CARD.PAGESTORM"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "rest_site",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "id": "CARD.FEAR"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.INVOKE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "id": "CARD.FLATTEN"
                                },
                                "was_picked": false
                            }
                        ],
                        "current_gold": 108,
                        "current_hp": 64,
                        "damage_taken": 0,
                        "gold_gained": 15,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.AXEBOTS_NORMAL",
                        "monster_ids": [
                            "MONSTER.AXEBOT",
                            "MONSTER.AXEBOT"
                        ],
                        "room_type": "monster",
                        "turns_taken": 3
                    }
                ]
            },
            {
                "map_point_type": "unknown",
                "player_stats": [
                    {
                        "current_gold": 108,
                        "current_hp": 64,
                        "damage_taken": 0,
                        "event_choices": [
                            {
                                "title": {
                                    "key": "RELIC_TRADER.pages.INITIAL.options.TOP.title",
                                    "table": "events"
                                },
                                "variables": {
                                    "TopRelicOwned": {
                                        "type": "DynamicString",
                                        "decimal_value": 0,
                                        "bool_value": false,
                                        "string_value": "Bone Flute"
                                    },
                                    "TopRelicNew": {
                                        "type": "DynamicString",
                                        "decimal_value": 0,
                                        "bool_value": false,
                                        "string_value": "Bellows"
                                    },
                                    "MiddleRelicOwned": {
                                        "type": "DynamicString",
                                        "decimal_value": 0,
                                        "bool_value": false,
                                        "string_value": "Happy Flower"
                                    },
                                    "MiddleRelicNew": {
                                        "type": "DynamicString",
                                        "decimal_value": 0,
                                        "bool_value": false,
                                        "string_value": "Ornamental Fan"
                                    },
                                    "BottomRelicOwned": {
                                        "type": "DynamicString",
                                        "decimal_value": 0,
                                        "bool_value": false,
                                        "string_value": "Reptile Trinket"
                                    },
                                    "BottomRelicNew": {
                                        "type": "DynamicString",
                                        "decimal_value": 0,
                                        "bool_value": false,
                                        "string_value": "Horn Cleat"
                                    }
                                }
                            }
                        ],
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "relic_choices": [
                            {
                                "choice": "RELIC.BELLOWS",
                                "was_picked": true
                            }
                        ],
                        "relics_removed": [
                            "RELIC.BONE_FLUTE"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "EVENT.RELIC_TRADER",
                        "room_type": "event",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "shop",
                "player_stats": [
                    {
                        "bought_colorless": [
                            "CARD.PRODUCTION"
                        ],
                        "card_choices": [
                            {
                                "card": {
                                    "id": "CARD.DRAIN_POWER"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.REAVE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.INVOKE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.WISP"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.COUNTDOWN"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.HIDDEN_GEM"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.PRODUCTION"
                            }
                        ],
                        "current_gold": 20,
                        "current_hp": 64,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 88,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.VULNERABLE_POTION",
                                "was_picked": false
                            },
                            {
                                "choice": "POTION.BLOCK_POTION",
                                "was_picked": false
                            },
                            {
                                "choice": "POTION.DEXTERITY_POTION",
                                "was_picked": false
                            }
                        ],
                        "relic_choices": [
                            {
                                "choice": "RELIC.VENERABLE_TEA_SET",
                                "was_picked": false
                            },
                            {
                                "choice": "RELIC.GAME_PIECE",
                                "was_picked": false
                            },
                            {
                                "choice": "RELIC.ROYAL_STAMP",
                                "was_picked": false
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "shop",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "rest_site",
                "player_stats": [
                    {
                        "current_gold": 20,
                        "current_hp": 64,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "rest_site_choices": [
                            "SMITH"
                        ],
                        "upgraded_cards": [
                            "CARD.PRODUCTION"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "rest_site",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "boss",
                "player_stats": [
                    {
                        "current_gold": 20,
                        "current_hp": 64,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 73,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.DOORMAKER_BOSS",
                        "monster_ids": [
                            "MONSTER.DOOR"
                        ],
                        "room_type": "boss",
                        "turns_taken": 5
                    }
                ]
            }
        ]
    ],
    "modifiers": [],
    "platform_type": "steam",
    "players": [
        {
            "character": "CHARACTER.NECROBINDER",
            "deck": [
                {
                    "floor_added_to_deck": 1,
                    "id": "CARD.DEFEND_NECROBINDER"
                },
                {
                    "floor_added_to_deck": 1,
                    "id": "CARD.DEFEND_NECROBINDER"
                },
                {
                    "floor_added_to_deck": 1,
                    "id": "CARD.DEFEND_NECROBINDER"
                },
                {
                    "floor_added_to_deck": 1,
                    "id": "CARD.BODYGUARD"
                },
                {
                    "floor_added_to_deck": 1,
                    "id": "CARD.UNLEASH"
                },
                {
                    "floor_added_to_deck": 1,
                    "id": "CARD.ASCENDERS_BANE"
                },
                {
                    "floor_added_to_deck": 2,
                    "id": "CARD.COUNTDOWN"
                },
                {
                    "enchantment": {
                        "amount": 2,
                        "id": "ENCHANTMENT.NIMBLE"
                    },
                    "floor_added_to_deck": 3,
                    "id": "CARD.DEATHS_DOOR"
                },
                {
                    "floor_added_to_deck": 4,
                    "id": "CARD.ENFEEBLING_TOUCH"
                },
                {
                    "current_upgrade_level": 1,
                    "floor_added_to_deck": 6,
                    "id": "CARD.LETHALITY"
                },
                {
                    "floor_added_to_deck": 8,
                    "id": "CARD.GRAVE_WARDEN"
                },
                {
                    "floor_added_to_deck": 9,
                    "id": "CARD.NEGATIVE_PULSE"
                },
                {
                    "current_upgrade_level": 1,
                    "floor_added_to_deck": 11,
                    "id": "CARD.PAGESTORM"
                },
                {
                    "current_upgrade_level": 1,
                    "floor_added_to_deck": 11,
                    "id": "CARD.NO_ESCAPE"
                },
                {
                    "floor_added_to_deck": 14,
                    "id": "CARD.DIRGE"
                },
                {
                    "floor_added_to_deck": 15,
                    "id": "CARD.FRIENDSHIP"
                },
                {
                    "floor_added_to_deck": 17,
                    "id": "CARD.NEUROSURGE"
                },
                {
                    "current_upgrade_level": 1,
                    "floor_added_to_deck": 19,
                    "id": "CARD.BORROWED_TIME"
                },
                {
                    "floor_added_to_deck": 20,
                    "id": "CARD.GRAVE_WARDEN"
                },
                {
                    "current_upgrade_level": 1,
                    "floor_added_to_deck": 21,
                    "id": "CARD.DEFY"
                },
                {
                    "floor_added_to_deck": 23,
                    "id": "CARD.BANSHEES_CRY"
                },
                {
                    "floor_added_to_deck": 25,
                    "id": "CARD.DANSE_MACABRE"
                },
                {
                    "floor_added_to_deck": 27,
                    "id": "CARD.NEGATIVE_PULSE"
                },
                {
                    "current_upgrade_level": 1,
                    "floor_added_to_deck": 30,
                    "id": "CARD.SCOURGE"
                },
                {
                    "floor_added_to_deck": 31,
                    "id": "CARD.SEANCE"
                },
                {
                    "current_upgrade_level": 1,
                    "floor_added_to_deck": 33,
                    "id": "CARD.DEMESNE"
                },
                {
                    "floor_added_to_deck": 35,
                    "id": "CARD.PARSE"
                },
                {
                    "floor_added_to_deck": 36,
                    "id": "CARD.SEANCE"
                },
                {
                    "current_upgrade_level": 1,
                    "floor_added_to_deck": 38,
                    "id": "CARD.SCOURGE"
                },
                {
                    "current_upgrade_level": 1,
                    "floor_added_to_deck": 39,
                    "id": "CARD.PAGESTORM"
                },
                {
                    "current_upgrade_level": 1,
                    "floor_added_to_deck": 46,
                    "id": "CARD.PRODUCTION"
                }
            ],
            "id": 1,
            "max_potion_slot_count": 2,
            "potions": [
                {
                    "id": "POTION.CLARITY",
                    "slot_index": 1
                }
            ],
            "relics": [
                {
                    "floor_added_to_deck": 18,
                    "id": "RELIC.PHYLACTERY_UNBOUND"
                },
                {
                    "floor_added_to_deck": 1,
                    "id": "RELIC.PRECARIOUS_SHEARS"
                },
                {
                    "floor_added_to_deck": 6,
                    "id": "RELIC.REPTILE_TRINKET"
                },
                {
                    "floor_added_to_deck": 9,
                    "id": "RELIC.BIG_HAT"
                },
                {
                    "floor_added_to_deck": 10,
                    "id": "RELIC.FESTIVE_POPPER"
                },
                {
                    "floor_added_to_deck": 14,
                    "id": "RELIC.STRAWBERRY"
                },
                {
                    "floor_added_to_deck": 18,
                    "id": "RELIC.TOUCH_OF_OROBAS",
                    "props": {
                        "model_ids": [
                            {
                                "name": "StarterRelic",
                                "value": "RELIC.BOUND_PHYLACTERY"
                            },
                            {
                                "name": "UpgradedRelic",
                                "value": "RELIC.PHYLACTERY_UNBOUND"
                            }
                        ]
                    }
                },
                {
                    "floor_added_to_deck": 23,
                    "id": "RELIC.VAJRA"
                },
                {
                    "floor_added_to_deck": 26,
                    "id": "RELIC.HAPPY_FLOWER",
                    "props": {
                        "ints": [
                            {
                                "name": "TurnsSeen",
                                "value": 0
                            }
                        ]
                    }
                },
                {
                    "floor_added_to_deck": 31,
                    "id": "RELIC.ART_OF_WAR"
                },
                {
                    "floor_added_to_deck": 34,
                    "id": "RELIC.JEWELED_MASK"
                },
                {
                    "floor_added_to_deck": 39,
                    "id": "RELIC.BAG_OF_PREPARATION"
                },
                {
                    "floor_added_to_deck": 41,
                    "id": "RELIC.GREMLIN_HORN"
                },
                {
                    "floor_added_to_deck": 42,
                    "id": "RELIC.GORGET"
                },
                {
                    "floor_added_to_deck": 45,
                    "id": "RELIC.BELLOWS"
                }
            ]
        }
    ],
    "run_time": 3138,
    "schema_version": 8,
    "seed": "C0BGT25PU4",
    "start_time": 1773331937,
    "was_abandoned": false,
    "win": true
}