{
    "acts": [
        "ACT.OVERGROWTH",
        "ACT.HIVE",
        "ACT.GLORY"
    ],
    "ascension": 0,
    "build_id": "v0.98.2",
    "game_mode": "standard",
    "killed_by_encounter": "NONE.NONE",
    "killed_by_event": "NONE.NONE",
    "map_point_history": [
        [
            {
                "map_point_type": "ancient",
                "player_stats": [
                    {
                        "ancient_choice": [
                            {
                                "TextKey": "ARCANE_SCROLL",
                                "title": {
                                    "key": "ARCANE_SCROLL.title",
                                    "table": "relics"
                                },
                                "was_chosen": false
                            },
                            {
                                "TextKey": "POMANDER",
                                "title": {
                                    "key": "POMANDER.title",
                                    "table": "relics"
                                },
                                "was_chosen": false
                            },
                            {
                                "TextKey": "PRECARIOUS_SHEARS",
                                "title": {
                                    "key": "PRECARIOUS_SHEARS.title",
                                    "table": "relics"
                                },
                                "was_chosen": true
                            }
                        ],
                        "cards_removed": [
                            {
                                "floor_added_to_deck": 1,
                                "id": "CARD.STRIKE_REGENT"
                            },
                            {
                                "floor_added_to_deck": 1,
                                "id": "CARD.STRIKE_REGENT"
                            }
                        ],
                        "current_gold": 99,
                        "current_hp": 62,
                        "damage_taken": 13,
                        "event_choices": [
                            {
                                "title": {
                                    "key": "PRECARIOUS_SHEARS.title",
                                    "table": "relics"
                                }
                            }
                        ],
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 75,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "relic_choices": [
                            {
                                "choice": "RELIC.PRECARIOUS_SHEARS",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "EVENT.NEOW",
                        "room_type": "event",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 2,
                                    "id": "CARD.GLOW"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.GLIMMER"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.KNOW_THY_PLACE"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.GLOW"
                            }
                        ],
                        "current_gold": 118,
                        "current_hp": 62,
                        "damage_taken": 0,
                        "gold_gained": 19,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.SHRINKER_BEETLE_WEAK",
                        "monster_ids": [
                            "MONSTER.SHRINKER_BEETLE"
                        ],
                        "room_type": "monster",
                        "turns_taken": 7
                    }
                ]
            },
            {
                "map_point_type": "unknown",
                "player_stats": [
                    {
                        "cards_gained": [
                            {
                                "id": "CARD.GUILTY",
                                "props": {
                                    "ints": [
                                        {
                                            "name": "CombatsSeen",
                                            "value": 0
                                        }
                                    ]
                                }
                            }
                        ],
                        "cards_removed": [
                            {
                                "floor_added_to_deck": 1,
                                "id": "CARD.DEFEND_REGENT"
                            }
                        ],
                        "current_gold": 118,
                        "current_hp": 62,
                        "damage_taken": 0,
                        "event_choices": [
                            {
                                "title": {
                                    "key": "WELLSPRING.pages.INITIAL.options.BATHE.title",
                                    "table": "events"
                                },
                                "variables": {
                                    "BatheCurses": {
                                        "type": "BaseDynamic",
                                        "decimal_value": 1,
                                        "bool_value": false,
                                        "string_value": null
                                    }
                                }
                            }
                        ],
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "EVENT.WELLSPRING",
                        "room_type": "event",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "shop",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "id": "CARD.STARDUST"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.WROUGHT_IN_WAR"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.TERRAFORMING"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.CLOAK_OF_STARS"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.BLACK_HOLE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.STRATAGEM"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.ETERNAL_ARMOR"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_removed": [
                            {
                                "floor_added_to_deck": 1,
                                "id": "CARD.STRIKE_REGENT"
                            }
                        ],
                        "current_gold": 43,
                        "current_hp": 62,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 75,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.BLESSING_OF_THE_FORGE",
                                "was_picked": false
                            },
                            {
                                "choice": "POTION.LIQUID_BRONZE",
                                "was_picked": false
                            },
                            {
                                "choice": "POTION.POWER_POTION",
                                "was_picked": false
                            }
                        ],
                        "relic_choices": [
                            {
                                "choice": "RELIC.ODDLY_SMOOTH_STONE",
                                "was_picked": false
                            },
                            {
                                "choice": "RELIC.BLOOD_VIAL",
                                "was_picked": false
                            },
                            {
                                "choice": "RELIC.BELT_BUCKLE",
                                "was_picked": false
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "shop",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "unknown",
                "player_stats": [
                    {
                        "cards_gained": [
                            {
                                "id": "CARD.SPOILS_MAP",
                                "props": {
                                    "ints": [
                                        {
                                            "name": "SpoilsActIndex",
                                            "value": 1
                                        }
                                    ]
                                }
                            }
                        ],
                        "current_gold": 43,
                        "current_hp": 62,
                        "damage_taken": 0,
                        "event_choices": [
                            {
                                "title": {
                                    "key": "THE_LEGENDS_WERE_TRUE.pages.INITIAL.options.NAB_THE_MAP.title",
                                    "table": "events"
                                },
                                "variables": {}
                            }
                        ],
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "EVENT.THE_LEGENDS_WERE_TRUE",
                        "room_type": "event",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 6,
                                    "id": "CARD.WROUGHT_IN_WAR"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.COSMIC_INDIFFERENCE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.REFLECT"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.WROUGHT_IN_WAR"
                            }
                        ],
                        "current_gold": 58,
                        "current_hp": 50,
                        "damage_taken": 12,
                        "gold_gained": 15,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.NIBBITS_WEAK",
                        "monster_ids": [
                            "MONSTER.NIBBIT"
                        ],
                        "room_type": "monster",
                        "turns_taken": 8
                    }
                ]
            },
            {
                "map_point_type": "rest_site",
                "player_stats": [
                    {
                        "current_gold": 58,
                        "current_hp": 50,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "rest_site_choices": [
                            "SMITH"
                        ],
                        "upgraded_cards": [
                            "CARD.WROUGHT_IN_WAR"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "rest_site",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "id": "CARD.SPECTRUM_SHIFT"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.GLOW"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.GUIDING_STAR"
                                },
                                "was_picked": false
                            }
                        ],
                        "current_gold": 71,
                        "current_hp": 49,
                        "damage_taken": 1,
                        "gold_gained": 13,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.MAZALETHS_GIFT",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.SLIMES_WEAK",
                        "monster_ids": [
                            "MONSTER.TWIG_SLIME_S",
                            "MONSTER.LEAF_SLIME_M",
                            "MONSTER.LEAF_SLIME_S"
                        ],
                        "room_type": "monster",
                        "turns_taken": 3
                    }
                ]
            },
            {
                "map_point_type": "rest_site",
                "player_stats": [
                    {
                        "current_gold": 71,
                        "current_hp": 71,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 22,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "rest_site_choices": [
                            "HEAL"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "rest_site",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "treasure",
                "player_stats": [
                    {
                        "current_gold": 113,
                        "current_hp": 71,
                        "damage_taken": 0,
                        "gold_gained": 42,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "relic_choices": [
                            {
                                "choice": "RELIC.PEN_NIB",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "treasure",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "unknown",
                "player_stats": [
                    {
                        "cards_transformed": [
                            {
                                "final_card": {
                                    "floor_added_to_deck": 11,
                                    "id": "CARD.TORIC_TOUGHNESS"
                                },
                                "original_card": {
                                    "floor_added_to_deck": 1,
                                    "id": "CARD.DEFEND_REGENT"
                                }
                            }
                        ],
                        "current_gold": 113,
                        "current_hp": 71,
                        "damage_taken": 0,
                        "event_choices": [
                            {
                                "title": {
                                    "key": "WOOD_CARVINGS.pages.INITIAL.options.TORUS.title",
                                    "table": "events"
                                },
                                "variables": {
                                    "BirdCard": {
                                        "type": "DynamicString",
                                        "decimal_value": 0,
                                        "bool_value": false,
                                        "string_value": "Picotazo"
                                    },
                                    "SnakeEnchantment": {
                                        "type": "DynamicString",
                                        "decimal_value": 0,
                                        "bool_value": false,
                                        "string_value": "Serpenteo"
                                    },
                                    "ToricCard": {
                                        "type": "DynamicString",
                                        "decimal_value": 0,
                                        "bool_value": false,
                                        "string_value": "Resistencia t\u00f3rica"
                                    }
                                }
                            }
                        ],
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "EVENT.WOOD_CARVINGS",
                        "room_type": "event",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "rest_site",
                "player_stats": [
                    {
                        "current_gold": 113,
                        "current_hp": 71,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "rest_site_choices": [
                            "SMITH"
                        ],
                        "upgraded_cards": [
                            "CARD.TORIC_TOUGHNESS"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "rest_site",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "elite",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 13,
                                    "id": "CARD.KINGLY_PUNCH"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.DECISIONS_DECISIONS"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.CLOAK_OF_STARS"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.KINGLY_PUNCH"
                            }
                        ],
                        "current_gold": 157,
                        "current_hp": 31,
                        "damage_taken": 40,
                        "gold_gained": 44,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.BLOCK_POTION",
                                "was_picked": true
                            }
                        ],
                        "relic_choices": [
                            {
                                "choice": "RELIC.LETTER_OPENER",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.BYGONE_EFFIGY_ELITE",
                        "monster_ids": [
                            "MONSTER.BYGONE_EFFIGY"
                        ],
                        "room_type": "elite",
                        "turns_taken": 6
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "id": "CARD.REFLECT"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.GUIDING_STAR"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.CRUSH_UNDER"
                                },
                                "was_picked": false
                            }
                        ],
                        "current_gold": 168,
                        "current_hp": 30,
                        "damage_taken": 1,
                        "gold_gained": 11,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.SPEED_POTION",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.OVERGROWTH_CRAWLERS",
                        "monster_ids": [
                            "MONSTER.SHRINKER_BEETLE",
                            "MONSTER.FUZZY_WURM_CRAWLER"
                        ],
                        "room_type": "monster",
                        "turns_taken": 6
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "id": "CARD.PHOTON_CUT"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.COLLISION_COURSE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.ASTRAL_PULSE"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_removed": [
                            {
                                "floor_added_to_deck": 3,
                                "id": "CARD.GUILTY",
                                "props": {
                                    "ints": [
                                        {
                                            "name": "CombatsSeen",
                                            "value": 5
                                        }
                                    ]
                                }
                            }
                        ],
                        "current_gold": 185,
                        "current_hp": 30,
                        "damage_taken": 0,
                        "gold_gained": 17,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.CUBEX_CONSTRUCT_NORMAL",
                        "monster_ids": [
                            "MONSTER.CUBEX_CONSTRUCT"
                        ],
                        "room_type": "monster",
                        "turns_taken": 3
                    }
                ]
            },
            {
                "map_point_type": "rest_site",
                "player_stats": [
                    {
                        "current_gold": 185,
                        "current_hp": 30,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "rest_site_choices": [
                            "SMITH"
                        ],
                        "upgraded_cards": [
                            "CARD.KINGLY_PUNCH"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "rest_site",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "boss",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 17,
                                    "id": "CARD.DECISIONS_DECISIONS"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.HEIRLOOM_HAMMER"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.GUARDS"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.DECISIONS_DECISIONS"
                            }
                        ],
                        "current_gold": 285,
                        "current_hp": 7,
                        "damage_taken": 23,
                        "gold_gained": 100,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.POWER_POTION",
                                "was_picked": true
                            }
                        ],
                        "potion_used": [
                            "POTION.MAZALETHS_GIFT",
                            "POTION.BLOCK_POTION",
                            "POTION.SPEED_POTION"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.THE_KIN_BOSS",
                        "monster_ids": [
                            "MONSTER.KIN_FOLLOWER",
                            "MONSTER.KIN_FOLLOWER",
                            "MONSTER.KIN_PRIEST"
                        ],
                        "room_type": "boss",
                        "turns_taken": 9
                    }
                ]
            }
        ],
        [
            {
                "map_point_type": "ancient",
                "player_stats": [
                    {
                        "ancient_choice": [
                            {
                                "TextKey": "ELECTRIC_SHRYMP",
                                "title": {
                                    "key": "ELECTRIC_SHRYMP.title",
                                    "table": "relics"
                                },
                                "was_chosen": true
                            },
                            {
                                "TextKey": "DRIFTWOOD",
                                "title": {
                                    "key": "DRIFTWOOD.title",
                                    "table": "relics"
                                },
                                "was_chosen": false
                            },
                            {
                                "TextKey": "TOUCH_OF_OROBAS",
                                "title": {
                                    "key": "TOUCH_OF_OROBAS.title",
                                    "table": "relics"
                                },
                                "was_chosen": false
                            }
                        ],
                        "cards_enchanted": [
                            {
                                "card": {
                                    "enchantment": {
                                        "amount": 1,
                                        "id": "ENCHANTMENT.IMBUED"
                                    },
                                    "floor_added_to_deck": 17,
                                    "id": "CARD.DECISIONS_DECISIONS"
                                },
                                "enchantment": "ENCHANTMENT.IMBUED"
                            }
                        ],
                        "current_gold": 285,
                        "current_hp": 75,
                        "damage_taken": 0,
                        "event_choices": [
                            {
                                "title": {
                                    "key": "ELECTRIC_SHRYMP.title",
                                    "table": "relics"
                                }
                            }
                        ],
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 68,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "relic_choices": [
                            {
                                "choice": "RELIC.ELECTRIC_SHRYMP",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "EVENT.OROBAS",
                        "room_type": "event",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "id": "CARD.COLLISION_COURSE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.KINGLY_KICK"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.CELESTIAL_MIGHT"
                                },
                                "was_picked": false
                            }
                        ],
                        "current_gold": 299,
                        "current_hp": 75,
                        "damage_taken": 0,
                        "gold_gained": 14,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.EXOSKELETONS_WEAK",
                        "monster_ids": [
                            "MONSTER.EXOSKELETON",
                            "MONSTER.EXOSKELETON",
                            "MONSTER.EXOSKELETON"
                        ],
                        "room_type": "monster",
                        "turns_taken": 4
                    }
                ]
            },
            {
                "map_point_type": "unknown",
                "player_stats": [
                    {
                        "cards_enchanted": [
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "enchantment": {
                                        "amount": 1,
                                        "id": "ENCHANTMENT.PERFECT_FIT"
                                    },
                                    "floor_added_to_deck": 6,
                                    "id": "CARD.WROUGHT_IN_WAR"
                                },
                                "enchantment": "ENCHANTMENT.PERFECT_FIT"
                            }
                        ],
                        "current_gold": 299,
                        "current_hp": 75,
                        "damage_taken": 0,
                        "event_choices": [
                            {
                                "title": {
                                    "key": "FIELD_OF_MAN_SIZED_HOLES.pages.INITIAL.options.ENTER_YOUR_HOLE.title",
                                    "table": "events"
                                },
                                "variables": {
                                    "ResistCurse": {
                                        "type": "DynamicString",
                                        "decimal_value": 0,
                                        "bool_value": false,
                                        "string_value": "Normalidad"
                                    },
                                    "Enchantment": {
                                        "type": "DynamicString",
                                        "decimal_value": 0,
                                        "bool_value": false,
                                        "string_value": "A medida"
                                    }
                                }
                            }
                        ],
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "EVENT.FIELD_OF_MAN_SIZED_HOLES",
                        "room_type": "event",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 21,
                                    "id": "CARD.CONQUEROR"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.CELESTIAL_MIGHT"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.PHOTON_CUT"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.CONQUEROR"
                            }
                        ],
                        "current_gold": 316,
                        "current_hp": 75,
                        "damage_taken": 0,
                        "gold_gained": 17,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.BEETLE_JUICE",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.BOWLBUGS_WEAK",
                        "monster_ids": [
                            "MONSTER.BOWLBUG_ROCK",
                            "MONSTER.BOWLBUG_EGG"
                        ],
                        "room_type": "monster",
                        "turns_taken": 3
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 22,
                                    "id": "CARD.COSMIC_INDIFFERENCE"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.SPOILS_OF_BATTLE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "id": "CARD.PALE_BLUE_DOT"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.COSMIC_INDIFFERENCE"
                            }
                        ],
                        "current_gold": 329,
                        "current_hp": 75,
                        "damage_taken": 0,
                        "gold_gained": 13,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.REGEN_POTION",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.HUNTER_KILLER_NORMAL",
                        "monster_ids": [
                            "MONSTER.HUNTER_KILLER"
                        ],
                        "room_type": "monster",
                        "turns_taken": 2
                    }
                ]
            },
            {
                "map_point_type": "shop",
                "player_stats": [
                    {
                        "bought_colorless": [
                            "CARD.HIDDEN_GEM"
                        ],
                        "card_choices": [
                            {
                                "card": {
                                    "id": "CARD.HEIRLOOM_HAMMER"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.KINGLY_KICK"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.GLITTERSTREAM"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.TERRAFORMING"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.FURNACE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.OMNISLICE"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.HIDDEN_GEM"
                            }
                        ],
                        "cards_removed": [
                            {
                                "floor_added_to_deck": 1,
                                "id": "CARD.STRIKE_REGENT"
                            }
                        ],
                        "current_gold": 64,
                        "current_hp": 75,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 265,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.EXPLOSIVE_AMPOULE",
                                "was_picked": false
                            },
                            {
                                "choice": "POTION.FLEX_POTION",
                                "was_picked": false
                            },
                            {
                                "choice": "POTION.STRENGTH_POTION",
                                "was_picked": false
                            }
                        ],
                        "relic_choices": [
                            {
                                "choice": "RELIC.BOWLER_HAT",
                                "was_picked": false
                            },
                            {
                                "choice": "RELIC.STRIKE_DUMMY",
                                "was_picked": false
                            },
                            {
                                "choice": "RELIC.DRAGON_FRUIT",
                                "was_picked": false
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "shop",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "id": "CARD.BULWARK"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.COSMIC_INDIFFERENCE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.TERRAFORMING"
                                },
                                "was_picked": false
                            }
                        ],
                        "current_gold": 82,
                        "current_hp": 75,
                        "damage_taken": 0,
                        "gold_gained": 18,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.TUNNELER_NORMAL",
                        "monster_ids": [
                            "MONSTER.BOWLBUG_EGG",
                            "MONSTER.TUNNELER"
                        ],
                        "room_type": "monster",
                        "turns_taken": 4
                    }
                ]
            },
            {
                "map_point_type": "elite",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "id": "CARD.SHINING_STRIKE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.HIDDEN_CACHE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.BOMBARDMENT"
                                },
                                "was_picked": false
                            }
                        ],
                        "current_gold": 127,
                        "current_hp": 53,
                        "damage_taken": 22,
                        "gold_gained": 45,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "relic_choices": [
                            {
                                "choice": "RELIC.LANTERN",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.DECIMILLIPEDE_ELITE",
                        "monster_ids": [
                            "MONSTER.DECIMILLIPEDE_SEGMENT_FRONT",
                            "MONSTER.DECIMILLIPEDE_SEGMENT_MIDDLE",
                            "MONSTER.DECIMILLIPEDE_SEGMENT_BACK"
                        ],
                        "room_type": "elite",
                        "turns_taken": 7
                    }
                ]
            },
            {
                "map_point_type": "treasure",
                "player_stats": [
                    {
                        "cards_removed": [
                            {
                                "floor_added_to_deck": 5,
                                "id": "CARD.SPOILS_MAP",
                                "props": {
                                    "ints": [
                                        {
                                            "name": "SpoilsActIndex",
                                            "value": 1
                                        }
                                    ]
                                }
                            }
                        ],
                        "completed_quests": [
                            "CARD.SPOILS_MAP"
                        ],
                        "current_gold": 773,
                        "current_hp": 53,
                        "damage_taken": 0,
                        "gold_gained": 646,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "relic_choices": [
                            {
                                "choice": "RELIC.MERCURY_HOURGLASS",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "treasure",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "unknown",
                "player_stats": [
                    {
                        "cards_enchanted": [
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "enchantment": {
                                        "amount": 8,
                                        "id": "ENCHANTMENT.VIGOROUS"
                                    },
                                    "floor_added_to_deck": 13,
                                    "id": "CARD.KINGLY_PUNCH"
                                },
                                "enchantment": "ENCHANTMENT.VIGOROUS"
                            }
                        ],
                        "current_gold": 773,
                        "current_hp": 47,
                        "damage_taken": 6,
                        "event_choices": [
                            {
                                "title": {
                                    "key": "STONE_OF_ALL_TIME.pages.INITIAL.options.PUSH.title",
                                    "table": "events"
                                },
                                "variables": {
                                    "DrinkRandomPotion": {
                                        "type": "DynamicString",
                                        "decimal_value": 0,
                                        "bool_value": false,
                                        "string_value": "Zumo de escarabajo"
                                    },
                                    "DrinkMaxHpGain": {
                                        "type": "BaseDynamic",
                                        "decimal_value": 10,
                                        "bool_value": false,
                                        "string_value": null
                                    },
                                    "PushHpLoss": {
                                        "type": "BaseDynamic",
                                        "decimal_value": 6,
                                        "bool_value": false,
                                        "string_value": null
                                    },
                                    "PushVigorousAmount": {
                                        "type": "BaseDynamic",
                                        "decimal_value": 8,
                                        "bool_value": false,
                                        "string_value": null
                                    }
                                }
                            }
                        ],
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "EVENT.STONE_OF_ALL_TIME",
                        "room_type": "event",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "shop",
                "player_stats": [
                    {
                        "bought_relics": [
                            "RELIC.PARRYING_SHIELD"
                        ],
                        "card_choices": [
                            {
                                "card": {
                                    "id": "CARD.CELESTIAL_MIGHT"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.PHOTON_CUT"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.CONQUEROR"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.STRATAGEM"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.SECRET_WEAPON"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.DECISIONS_DECISIONS"
                            },
                            {
                                "id": "CARD.PARRY"
                            }
                        ],
                        "cards_removed": [
                            {
                                "floor_added_to_deck": 1,
                                "id": "CARD.DEFEND_REGENT"
                            }
                        ],
                        "current_gold": 221,
                        "current_hp": 47,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 552,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.OROBIC_ACID",
                                "was_picked": false
                            },
                            {
                                "choice": "POTION.SKILL_POTION",
                                "was_picked": false
                            },
                            {
                                "choice": "POTION.GAMBLERS_BREW",
                                "was_picked": false
                            }
                        ],
                        "relic_choices": [
                            {
                                "choice": "RELIC.PARRYING_SHIELD",
                                "was_picked": true
                            },
                            {
                                "choice": "RELIC.UNCEASING_TOP",
                                "was_picked": false
                            },
                            {
                                "choice": "RELIC.GNARLED_HAMMER",
                                "was_picked": false
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "shop",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "rest_site",
                "player_stats": [
                    {
                        "current_gold": 221,
                        "current_hp": 47,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "rest_site_choices": [
                            "SMITH"
                        ],
                        "upgraded_cards": [
                            "CARD.PARRY"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "rest_site",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "floor_added_to_deck": 30,
                                    "id": "CARD.BLACK_HOLE"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.CLOAK_OF_STARS"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "id": "CARD.CELESTIAL_MIGHT"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "current_upgrade_level": 1,
                                "id": "CARD.BLACK_HOLE"
                            }
                        ],
                        "current_gold": 241,
                        "current_hp": 47,
                        "damage_taken": 0,
                        "gold_gained": 20,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.EXOSKELETONS_NORMAL",
                        "monster_ids": [
                            "MONSTER.EXOSKELETON",
                            "MONSTER.EXOSKELETON",
                            "MONSTER.EXOSKELETON",
                            "MONSTER.EXOSKELETON"
                        ],
                        "room_type": "monster",
                        "turns_taken": 1
                    }
                ]
            },
            {
                "map_point_type": "unknown",
                "player_stats": [
                    {
                        "current_gold": 141,
                        "current_hp": 54,
                        "damage_taken": 0,
                        "event_choices": [
                            {
                                "title": {
                                    "key": "WELCOME_TO_WONGOS.pages.INITIAL.options.BARGAIN_BIN.title",
                                    "table": "events"
                                },
                                "variables": {
                                    "BargainBinCost": {
                                        "type": "BaseDynamic",
                                        "decimal_value": 100,
                                        "bool_value": false,
                                        "string_value": null
                                    },
                                    "MysteryBoxCost": {
                                        "type": "BaseDynamic",
                                        "decimal_value": 300,
                                        "bool_value": false,
                                        "string_value": null
                                    },
                                    "FeaturedItemCost": {
                                        "type": "BaseDynamic",
                                        "decimal_value": 200,
                                        "bool_value": false,
                                        "string_value": null
                                    },
                                    "MysteryBoxRelicCount": {
                                        "type": "BaseDynamic",
                                        "decimal_value": 3,
                                        "bool_value": false,
                                        "string_value": null
                                    },
                                    "MysteryBoxCombatCount": {
                                        "type": "BaseDynamic",
                                        "decimal_value": 5,
                                        "bool_value": false,
                                        "string_value": null
                                    },
                                    "WongoPointAmount": {
                                        "type": "BaseDynamic",
                                        "decimal_value": 32,
                                        "bool_value": false,
                                        "string_value": null
                                    },
                                    "RemainingWongoPointAmount": {
                                        "type": "BaseDynamic",
                                        "decimal_value": 1968,
                                        "bool_value": false,
                                        "string_value": null
                                    },
                                    "TotalWongoBadgeAmount": {
                                        "type": "BaseDynamic",
                                        "decimal_value": 0,
                                        "bool_value": false,
                                        "string_value": null
                                    },
                                    "RandomRelic": {
                                        "type": "DynamicString",
                                        "decimal_value": 0,
                                        "bool_value": false,
                                        "string_value": "Reloj de bolsillo"
                                    }
                                }
                            }
                        ],
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 100,
                        "gold_stolen": 0,
                        "hp_healed": 7,
                        "max_hp": 82,
                        "max_hp_gained": 7,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "relic_choices": [
                            {
                                "choice": "RELIC.STRAWBERRY",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "EVENT.WELCOME_TO_WONGOS",
                        "room_type": "event",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "rest_site",
                "player_stats": [
                    {
                        "current_gold": 141,
                        "current_hp": 54,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 82,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "rest_site_choices": [
                            "SMITH"
                        ],
                        "upgraded_cards": [
                            "CARD.DECISIONS_DECISIONS"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "rest_site",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "boss",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 33,
                                    "id": "CARD.THE_SMITH"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.COMET"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.BUNDLE_OF_JOY"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.THE_SMITH"
                            }
                        ],
                        "current_gold": 241,
                        "current_hp": 54,
                        "damage_taken": 0,
                        "gold_gained": 100,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 82,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.ENERGY_POTION",
                                "was_picked": true
                            }
                        ],
                        "potion_discarded": [
                            "POTION.REGEN_POTION"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.THE_INSATIABLE_BOSS",
                        "monster_ids": [
                            "MONSTER.THE_INSATIABLE"
                        ],
                        "room_type": "boss",
                        "turns_taken": 5
                    }
                ]
            }
        ],
        [
            {
                "map_point_type": "ancient",
                "player_stats": [
                    {
                        "ancient_choice": [
                            {
                                "TextKey": "SAI",
                                "title": {
                                    "key": "SAI.title",
                                    "table": "relics"
                                },
                                "was_chosen": false
                            },
                            {
                                "TextKey": "WAR_HAMMER",
                                "title": {
                                    "key": "WAR_HAMMER.title",
                                    "table": "relics"
                                },
                                "was_chosen": false
                            },
                            {
                                "TextKey": "THROWING_AXE",
                                "title": {
                                    "key": "THROWING_AXE.title",
                                    "table": "relics"
                                },
                                "was_chosen": true
                            }
                        ],
                        "current_gold": 241,
                        "current_hp": 82,
                        "damage_taken": 0,
                        "event_choices": [
                            {
                                "title": {
                                    "key": "THROWING_AXE.title",
                                    "table": "relics"
                                }
                            }
                        ],
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 28,
                        "max_hp": 82,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "relic_choices": [
                            {
                                "choice": "RELIC.THROWING_AXE",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "EVENT.TANX",
                        "room_type": "event",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "id": "CARD.GATHER_LIGHT"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "id": "CARD.WROUGHT_IN_WAR"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.BLACK_HOLE"
                                },
                                "was_picked": false
                            }
                        ],
                        "current_gold": 253,
                        "current_hp": 82,
                        "damage_taken": 0,
                        "gold_gained": 12,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 82,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.TURRET_OPERATOR_WEAK",
                        "monster_ids": [
                            "MONSTER.LIVING_SHIELD",
                            "MONSTER.TURRET_OPERATOR"
                        ],
                        "room_type": "monster",
                        "turns_taken": 1
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "id": "CARD.ROYALTIES"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "id": "CARD.PILLAR_OF_CREATION"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.GATHER_LIGHT"
                                },
                                "was_picked": false
                            }
                        ],
                        "current_gold": 264,
                        "current_hp": 82,
                        "damage_taken": 0,
                        "gold_gained": 11,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 82,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.SCROLLS_OF_BITING_WEAK",
                        "monster_ids": [
                            "MONSTER.SCROLL_OF_BITING",
                            "MONSTER.SCROLL_OF_BITING",
                            "MONSTER.SCROLL_OF_BITING"
                        ],
                        "room_type": "monster",
                        "turns_taken": 2
                    }
                ]
            },
            {
                "map_point_type": "unknown",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "id": "CARD.FOREGONE_CONCLUSION"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "id": "CARD.GUARDS"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "id": "CARD.THE_SMITH"
                                },
                                "was_picked": false
                            }
                        ],
                        "current_gold": 264,
                        "current_hp": 82,
                        "damage_taken": 0,
                        "event_choices": [
                            {
                                "title": {
                                    "key": "THE_FUTURE_OF_POTIONS.pages.INITIAL.options.POTION.title",
                                    "table": "events"
                                },
                                "variables": {
                                    "Rarity": {
                                        "type": "String",
                                        "decimal_value": 0,
                                        "bool_value": false,
                                        "string_value": "Rara"
                                    }
                                }
                            }
                        ],
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 82,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_discarded": [
                            "POTION.BEETLE_JUICE"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "EVENT.THE_FUTURE_OF_POTIONS",
                        "room_type": "event",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "id": "CARD.MONOLOGUE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "id": "CARD.CLOAK_OF_STARS"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.GLOW"
                                },
                                "was_picked": false
                            }
                        ],
                        "current_gold": 278,
                        "current_hp": 82,
                        "damage_taken": 0,
                        "gold_gained": 14,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 82,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.DEXTERITY_POTION",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.SLIMED_BERSERKER_NORMAL",
                        "monster_ids": [
                            "MONSTER.SLIMED_BERSERKER"
                        ],
                        "room_type": "monster",
                        "turns_taken": 1
                    }
                ]
            },
            {
                "map_point_type": "rest_site",
                "player_stats": [
                    {
                        "current_gold": 278,
                        "current_hp": 82,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 82,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "rest_site_choices": [
                            "SMITH"
                        ],
                        "upgraded_cards": [
                            "CARD.THE_SMITH"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "rest_site",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "elite",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "id": "CARD.KNOCKOUT_BLOW"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "id": "CARD.HIDDEN_CACHE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.PROPHESIZE"
                                },
                                "was_picked": false
                            }
                        ],
                        "current_gold": 322,
                        "current_hp": 82,
                        "damage_taken": 0,
                        "gold_gained": 44,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 82,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.BLESSING_OF_THE_FORGE",
                                "was_picked": true
                            }
                        ],
                        "potion_discarded": [
                            "POTION.DEXTERITY_POTION"
                        ],
                        "relic_choices": [
                            {
                                "choice": "RELIC.BELLOWS",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.MECHA_KNIGHT_ELITE",
                        "monster_ids": [
                            "MONSTER.MECHA_KNIGHT"
                        ],
                        "room_type": "elite",
                        "turns_taken": 1
                    }
                ]
            },
            {
                "map_point_type": "treasure",
                "player_stats": [
                    {
                        "current_gold": 368,
                        "current_hp": 82,
                        "damage_taken": 0,
                        "gold_gained": 46,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 82,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "relic_choices": [
                            {
                                "choice": "RELIC.ETERNAL_FEATHER",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "treasure",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "rest_site",
                "player_stats": [
                    {
                        "current_gold": 368,
                        "current_hp": 82,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 82,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "rest_site_choices": [
                            "SMITH"
                        ],
                        "upgraded_cards": [
                            "CARD.HIDDEN_GEM"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "rest_site",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "unknown",
                "player_stats": [
                    {
                        "cards_removed": [
                            {
                                "current_upgrade_level": 1,
                                "floor_added_to_deck": 28,
                                "id": "CARD.PARRY"
                            }
                        ],
                        "current_gold": 368,
                        "current_hp": 82,
                        "damage_taken": 0,
                        "event_choices": [
                            {
                                "title": {
                                    "key": "SLIPPERY_BRIDGE.pages.INITIAL.options.OVERCOME.title",
                                    "table": "events"
                                },
                                "variables": {
                                    "RandomCard": {
                                        "type": "DynamicString",
                                        "decimal_value": 0,
                                        "bool_value": false,
                                        "string_value": "Parada+"
                                    },
                                    "HpLoss": {
                                        "type": "BaseDynamic",
                                        "decimal_value": 3,
                                        "bool_value": false,
                                        "string_value": null
                                    }
                                }
                            }
                        ],
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 82,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "EVENT.SLIPPERY_BRIDGE",
                        "room_type": "event",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "shop",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "id": "CARD.PHOTON_CUT"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.STARDUST"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.SUMMON_FORTH"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.GATHER_LIGHT"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.PARRY"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.MIND_BLAST"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.SECRET_WEAPON"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_removed": [
                            {
                                "floor_added_to_deck": 1,
                                "id": "CARD.DEFEND_REGENT"
                            }
                        ],
                        "current_gold": 218,
                        "current_hp": 82,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 150,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 82,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.SPEED_POTION",
                                "was_picked": false
                            },
                            {
                                "choice": "POTION.RADIANT_TINCTURE",
                                "was_picked": false
                            },
                            {
                                "choice": "POTION.SWIFT_POTION",
                                "was_picked": false
                            }
                        ],
                        "relic_choices": [
                            {
                                "choice": "RELIC.AKABEKO",
                                "was_picked": false
                            },
                            {
                                "choice": "RELIC.STONE_CRACKER",
                                "was_picked": false
                            },
                            {
                                "choice": "RELIC.THE_ABACUS",
                                "was_picked": false
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "shop",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "elite",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "id": "CARD.CRUSH_UNDER"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "id": "CARD.CONVERGENCE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "id": "CARD.PARTICLE_WALL"
                                },
                                "was_picked": false
                            }
                        ],
                        "current_gold": 261,
                        "current_hp": 82,
                        "damage_taken": 0,
                        "gold_gained": 43,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 82,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "relic_choices": [
                            {
                                "choice": "RELIC.HAPPY_FLOWER",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.SOUL_NEXUS_ELITE",
                        "monster_ids": [
                            "MONSTER.SOUL_NEXUS"
                        ],
                        "room_type": "elite",
                        "turns_taken": 1
                    }
                ]
            },
            {
                "map_point_type": "unknown",
                "player_stats": [
                    {
                        "current_gold": 161,
                        "current_hp": 82,
                        "damage_taken": 0,
                        "event_choices": [
                            {
                                "title": {
                                    "key": "RANWID_THE_ELDER.pages.INITIAL.options.GOLD.title",
                                    "table": "events"
                                },
                                "variables": {
                                    "Potion": {
                                        "type": "DynamicString",
                                        "decimal_value": 0,
                                        "bool_value": false,
                                        "string_value": "Bendici\u00f3n de la forja"
                                    },
                                    "Relic": {
                                        "type": "DynamicString",
                                        "decimal_value": 0,
                                        "bool_value": false,
                                        "string_value": "Flor alegre"
                                    }
                                }
                            }
                        ],
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 100,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 82,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "relic_choices": [
                            {
                                "choice": "RELIC.WAR_PAINT",
                                "was_picked": true
                            }
                        ],
                        "upgraded_cards": [
                            "CARD.DECISIONS_DECISIONS",
                            "CARD.VENERATE"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "EVENT.RANWID_THE_ELDER",
                        "room_type": "event",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "rest_site",
                "player_stats": [
                    {
                        "current_gold": 161,
                        "current_hp": 82,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 82,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "rest_site_choices": [
                            "SMITH"
                        ],
                        "upgraded_cards": [
                            "CARD.CONQUEROR"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "rest_site",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "boss",
                "player_stats": [
                    {
                        "current_gold": 161,
                        "current_hp": 82,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 82,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.QUEEN_BOSS",
                        "monster_ids": [
                            "MONSTER.TORCH_HEAD_AMALGAM",
                            "MONSTER.QUEEN"
                        ],
                        "room_type": "boss",
                        "turns_taken": 1
                    }
                ]
            }
        ]
    ],
    "modifiers": [],
    "platform_type": "steam",
    "players": [
        {
            "character": "CHARACTER.REGENT",
            "deck": [
                {
                    "floor_added_to_deck": 1,
                    "id": "CARD.FALLING_STAR"
                },
                {
                    "current_upgrade_level": 1,
                    "floor_added_to_deck": 1,
                    "id": "CARD.VENERATE"
                },
                {
                    "floor_added_to_deck": 2,
                    "id": "CARD.GLOW"
                },
                {
                    "current_upgrade_level": 1,
                    "enchantment": {
                        "amount": 1,
                        "id": "ENCHANTMENT.PERFECT_FIT"
                    },
                    "floor_added_to_deck": 6,
                    "id": "CARD.WROUGHT_IN_WAR"
                },
                {
                    "current_upgrade_level": 1,
                    "floor_added_to_deck": 11,
                    "id": "CARD.TORIC_TOUGHNESS"
                },
                {
                    "current_upgrade_level": 1,
                    "enchantment": {
                        "amount": 8,
                        "id": "ENCHANTMENT.VIGOROUS"
                    },
                    "floor_added_to_deck": 13,
                    "id": "CARD.KINGLY_PUNCH"
                },
                {
                    "current_upgrade_level": 1,
                    "enchantment": {
                        "amount": 1,
                        "id": "ENCHANTMENT.IMBUED"
                    },
                    "floor_added_to_deck": 17,
                    "id": "CARD.DECISIONS_DECISIONS"
                },
                {
                    "current_upgrade_level": 1,
                    "floor_added_to_deck": 21,
                    "id": "CARD.CONQUEROR"
                },
                {
                    "floor_added_to_deck": 22,
                    "id": "CARD.COSMIC_INDIFFERENCE"
                },
                {
                    "current_upgrade_level": 1,
                    "floor_added_to_deck": 23,
                    "id": "CARD.HIDDEN_GEM"
                },
                {
                    "current_upgrade_level": 1,
                    "floor_added_to_deck": 28,
                    "id": "CARD.DECISIONS_DECISIONS"
                },
                {
                    "current_upgrade_level": 1,
                    "floor_added_to_deck": 30,
                    "id": "CARD.BLACK_HOLE"
                },
                {
                    "current_upgrade_level": 1,
                    "floor_added_to_deck": 33,
                    "id": "CARD.THE_SMITH"
                }
            ],
            "id": 1,
            "max_potion_slot_count": 3,
            "potions": [
                {
                    "id": "POTION.POWER_POTION",
                    "slot_index": 0
                },
                {
                    "id": "POTION.BLESSING_OF_THE_FORGE",
                    "slot_index": 1
                },
                {
                    "id": "POTION.ENERGY_POTION",
                    "slot_index": 2
                }
            ],
            "relics": [
                {
                    "floor_added_to_deck": 1,
                    "id": "RELIC.DIVINE_RIGHT"
                },
                {
                    "floor_added_to_deck": 1,
                    "id": "RELIC.PRECARIOUS_SHEARS"
                },
                {
                    "floor_added_to_deck": 10,
                    "id": "RELIC.PEN_NIB",
                    "props": {
                        "ints": [
                            {
                                "name": "AttacksPlayed",
                                "value": 4
                            }
                        ]
                    }
                },
                {
                    "floor_added_to_deck": 13,
                    "id": "RELIC.LETTER_OPENER"
                },
                {
                    "floor_added_to_deck": 18,
                    "id": "RELIC.ELECTRIC_SHRYMP"
                },
                {
                    "floor_added_to_deck": 25,
                    "id": "RELIC.LANTERN"
                },
                {
                    "floor_added_to_deck": 26,
                    "id": "RELIC.MERCURY_HOURGLASS"
                },
                {
                    "floor_added_to_deck": 28,
                    "id": "RELIC.PARRYING_SHIELD"
                },
                {
                    "floor_added_to_deck": 31,
                    "id": "RELIC.STRAWBERRY"
                },
                {
                    "floor_added_to_deck": 34,
                    "id": "RELIC.THROWING_AXE"
                },
                {
                    "floor_added_to_deck": 40,
                    "id": "RELIC.BELLOWS"
                },
                {
                    "floor_added_to_deck": 41,
                    "id": "RELIC.ETERNAL_FEATHER"
                },
                {
                    "floor_added_to_deck": 45,
                    "id": "RELIC.HAPPY_FLOWER",
                    "props": {
                        "ints": [
                            {
                                "name": "TurnsSeen",
                                "value": 1
                            }
                        ]
                    }
                },
                {
                    "floor_added_to_deck": 46,
                    "id": "RELIC.WAR_PAINT"
                }
            ]
        }
    ],
    "run_time": 2653,
    "schema_version": 8,
    "seed": "MVCEACV9TE",
    "start_time": 1772984431,
    "was_abandoned": false,
    "win": true
}