{
    "acts": [
        "ACT.OVERGROWTH",
        "ACT.HIVE",
        "ACT.GLORY"
    ],
    "ascension": 5,
    "build_id": "v0.99.1",
    "game_mode": "standard",
    "killed_by_encounter": "ENCOUNTER.RUBY_RAIDERS_NORMAL",
    "killed_by_event": "NONE.NONE",
    "map_point_history": [
        [
            {
                "map_point_type": "ancient",
                "player_stats": [
                    {
                        "ancient_choice": [
                            {
                                "TextKey": "NEW_LEAF",
                                "title": {
                                    "key": "NEW_LEAF.title",
                                    "table": "relics"
                                },
                                "was_chosen": true
                            },
                            {
                                "TextKey": "POMANDER",
                                "title": {
                                    "key": "POMANDER.title",
                                    "table": "relics"
                                },
                                "was_chosen": false
                            },
                            {
                                "TextKey": "LARGE_CAPSULE",
                                "title": {
                                    "key": "LARGE_CAPSULE.title",
                                    "table": "relics"
                                },
                                "was_chosen": false
                            }
                        ],
                        "cards_transformed": [
                            {
                                "final_card": {
                                    "floor_added_to_deck": 1,
                                    "id": "CARD.NEUTRON_AEGIS"
                                },
                                "original_card": {
                                    "floor_added_to_deck": 1,
                                    "id": "CARD.STRIKE_REGENT"
                                }
                            }
                        ],
                        "current_gold": 99,
                        "current_hp": 60,
                        "damage_taken": 0,
                        "event_choices": [
                            {
                                "title": {
                                    "key": "NEW_LEAF.title",
                                    "table": "relics"
                                }
                            }
                        ],
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 60,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "relic_choices": [
                            {
                                "choice": "RELIC.NEW_LEAF",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "EVENT.NEOW",
                        "room_type": "event",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 2,
                                    "id": "CARD.GLOW"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.CLOAK_OF_STARS"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.SHINING_STRIKE"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.GLOW"
                            }
                        ],
                        "current_gold": 112,
                        "current_hp": 60,
                        "damage_taken": 0,
                        "gold_gained": 13,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.FUZZY_WURM_CRAWLER_WEAK",
                        "monster_ids": [
                            "MONSTER.FUZZY_WURM_CRAWLER"
                        ],
                        "room_type": "monster",
                        "turns_taken": 7
                    }
                ]
            },
            {
                "map_point_type": "unknown",
                "player_stats": [
                    {
                        "cards_removed": [
                            {
                                "floor_added_to_deck": 1,
                                "id": "CARD.STRIKE_REGENT"
                            }
                        ],
                        "current_gold": 112,
                        "current_hp": 49,
                        "damage_taken": 11,
                        "event_choices": [
                            {
                                "title": {
                                    "key": "DENSE_VEGETATION.pages.INITIAL.options.TRUDGE_ON.title",
                                    "table": "events"
                                }
                            }
                        ],
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "EVENT.DENSE_VEGETATION",
                        "room_type": "event",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 4,
                                    "id": "CARD.CONVERGENCE"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.PARRY"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.KNOW_THY_PLACE"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.CONVERGENCE"
                            }
                        ],
                        "current_gold": 120,
                        "current_hp": 43,
                        "damage_taken": 6,
                        "gold_gained": 8,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.SLIMES_WEAK",
                        "monster_ids": [
                            "MONSTER.LEAF_SLIME_S",
                            "MONSTER.TWIG_SLIME_M",
                            "MONSTER.TWIG_SLIME_S"
                        ],
                        "room_type": "monster",
                        "turns_taken": 6
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 5,
                                    "id": "CARD.CHILD_OF_THE_STARS"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.HEGEMONY"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.PALE_BLUE_DOT"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.CHILD_OF_THE_STARS"
                            }
                        ],
                        "current_gold": 130,
                        "current_hp": 41,
                        "damage_taken": 2,
                        "gold_gained": 10,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.SWIFT_POTION",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.NIBBITS_WEAK",
                        "monster_ids": [
                            "MONSTER.NIBBIT"
                        ],
                        "room_type": "monster",
                        "turns_taken": 6
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 6,
                                    "id": "CARD.KINGLY_PUNCH"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.LUNAR_BLAST"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.COLLISION_COURSE"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.KINGLY_PUNCH"
                            }
                        ],
                        "current_gold": 138,
                        "current_hp": 2,
                        "damage_taken": 39,
                        "gold_gained": 8,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.SLIMES_NORMAL",
                        "monster_ids": [
                            "MONSTER.TWIG_SLIME_M",
                            "MONSTER.LEAF_SLIME_M",
                            "MONSTER.TWIG_SLIME_S",
                            "MONSTER.LEAF_SLIME_S"
                        ],
                        "room_type": "monster",
                        "turns_taken": 14
                    }
                ]
            },
            {
                "map_point_type": "rest_site",
                "player_stats": [
                    {
                        "current_gold": 138,
                        "current_hp": 24,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 22,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "rest_site_choices": [
                            "HEAL"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "rest_site",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "current_gold": 138,
                        "current_hp": 0,
                        "damage_taken": 18,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 75,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.RUBY_RAIDERS_NORMAL",
                        "monster_ids": [
                            "MONSTER.TRACKER_RUBY_RAIDER",
                            "MONSTER.ASSASSIN_RUBY_RAIDER",
                            "MONSTER.CROSSBOW_RUBY_RAIDER"
                        ],
                        "room_type": "monster",
                        "turns_taken": 3
                    }
                ]
            }
        ]
    ],
    "modifiers": [],
    "platform_type": "steam",
    "players": [
        {
            "character": "CHARACTER.REGENT",
            "deck": [
                {
                    "floor_added_to_deck": 1,
                    "id": "CARD.STRIKE_REGENT"
                },
                {
                    "floor_added_to_deck": 1,
                    "id": "CARD.STRIKE_REGENT"
                },
                {
                    "floor_added_to_deck": 1,
                    "id": "CARD.DEFEND_REGENT"
                },
                {
                    "floor_added_to_deck": 1,
                    "id": "CARD.DEFEND_REGENT"
                },
                {
                    "floor_added_to_deck": 1,
                    "id": "CARD.DEFEND_REGENT"
                },
                {
                    "floor_added_to_deck": 1,
                    "id": "CARD.DEFEND_REGENT"
                },
                {
                    "floor_added_to_deck": 1,
                    "id": "CARD.FALLING_STAR"
                },
                {
                    "floor_added_to_deck": 1,
                    "id": "CARD.VENERATE"
                },
                {
                    "floor_added_to_deck": 1,
                    "id": "CARD.ASCENDERS_BANE"
                },
                {
                    "floor_added_to_deck": 1,
                    "id": "CARD.NEUTRON_AEGIS"
                },
                {
                    "floor_added_to_deck": 2,
                    "id": "CARD.GLOW"
                },
                {
                    "floor_added_to_deck": 4,
                    "id": "CARD.CONVERGENCE"
                },
                {
                    "floor_added_to_deck": 5,
                    "id": "CARD.CHILD_OF_THE_STARS"
                },
                {
                    "floor_added_to_deck": 6,
                    "id": "CARD.KINGLY_PUNCH"
                }
            ],
            "id": 1,
            "max_potion_slot_count": 2,
            "potions": [
                {
                    "id": "POTION.SWIFT_POTION",
                    "slot_index": 0
                }
            ],
            "relics": [
                {
                    "floor_added_to_deck": 1,
                    "id": "RELIC.DIVINE_RIGHT"
                },
                {
                    "floor_added_to_deck": 1,
                    "id": "RELIC.NEW_LEAF"
                }
            ]
        }
    ],
    "run_time": 985,
    "schema_version": 8,
    "seed": "CDXT7JK15T",
    "start_time": 1773801653,
    "was_abandoned": true,
    "win": false
}