{
    "acts": [
        "ACT.OVERGROWTH",
        "ACT.HIVE",
        "ACT.GLORY"
    ],
    "ascension": 0,
    "build_id": "v0.98.2",
    "game_mode": "standard",
    "killed_by_encounter": "NONE.NONE",
    "killed_by_event": "NONE.NONE",
    "map_point_history": [
        [
            {
                "map_point_type": "ancient",
                "player_stats": [
                    {
                        "ancient_choice": [
                            {
                                "TextKey": "GOLDEN_PEARL",
                                "title": {
                                    "key": "GOLDEN_PEARL.title",
                                    "table": "relics"
                                },
                                "was_chosen": false
                            },
                            {
                                "TextKey": "ARCANE_SCROLL",
                                "title": {
                                    "key": "ARCANE_SCROLL.title",
                                    "table": "relics"
                                },
                                "was_chosen": false
                            },
                            {
                                "TextKey": "SILVER_CRUCIBLE",
                                "title": {
                                    "key": "SILVER_CRUCIBLE.title",
                                    "table": "relics"
                                },
                                "was_chosen": true
                            }
                        ],
                        "current_gold": 99,
                        "current_hp": 70,
                        "damage_taken": 0,
                        "event_choices": [
                            {
                                "title": {
                                    "key": "SILVER_CRUCIBLE.title",
                                    "table": "relics"
                                }
                            }
                        ],
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 70,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "relic_choices": [
                            {
                                "choice": "RELIC.SILVER_CRUCIBLE",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "EVENT.NEOW",
                        "room_type": "event",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "floor_added_to_deck": 2,
                                    "id": "CARD.BOUNCING_FLASK"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "id": "CARD.UNTOUCHABLE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "id": "CARD.FLICK_FLACK"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "current_upgrade_level": 1,
                                "id": "CARD.BOUNCING_FLASK"
                            }
                        ],
                        "current_gold": 112,
                        "current_hp": 67,
                        "damage_taken": 3,
                        "gold_gained": 13,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.SHRINKER_BEETLE_WEAK",
                        "monster_ids": [
                            "MONSTER.SHRINKER_BEETLE"
                        ],
                        "room_type": "monster",
                        "turns_taken": 5
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "floor_added_to_deck": 3,
                                    "id": "CARD.DEFLECT"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "id": "CARD.BACKFLIP"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "id": "CARD.INFINITE_BLADES"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "current_upgrade_level": 1,
                                "id": "CARD.DEFLECT"
                            }
                        ],
                        "current_gold": 127,
                        "current_hp": 66,
                        "damage_taken": 1,
                        "gold_gained": 15,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.SLIMES_WEAK",
                        "monster_ids": [
                            "MONSTER.LEAF_SLIME_S",
                            "MONSTER.TWIG_SLIME_M",
                            "MONSTER.TWIG_SLIME_S"
                        ],
                        "room_type": "monster",
                        "turns_taken": 4
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "floor_added_to_deck": 4,
                                    "id": "CARD.FLECHETTES"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "id": "CARD.PIERCING_WAIL"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "id": "CARD.ANTICIPATE"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "current_upgrade_level": 1,
                                "id": "CARD.FLECHETTES"
                            }
                        ],
                        "current_gold": 142,
                        "current_hp": 66,
                        "damage_taken": 0,
                        "gold_gained": 15,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.FUZZY_WURM_CRAWLER_WEAK",
                        "monster_ids": [
                            "MONSTER.FUZZY_WURM_CRAWLER"
                        ],
                        "room_type": "monster",
                        "turns_taken": 4
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "id": "CARD.DAGGER_THROW"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.ASSASSINATE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.UNTOUCHABLE"
                                },
                                "was_picked": false
                            }
                        ],
                        "current_gold": 162,
                        "current_hp": 64,
                        "damage_taken": 2,
                        "gold_gained": 20,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.POWER_POTION",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.SNAPPING_JAXFRUIT_NORMAL",
                        "monster_ids": [
                            "MONSTER.SNAPPING_JAXFRUIT",
                            "MONSTER.FLYCONID"
                        ],
                        "room_type": "monster",
                        "turns_taken": 5
                    }
                ]
            },
            {
                "map_point_type": "elite",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 6,
                                    "id": "CARD.EXPERTISE"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.PINPOINT"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.SLICE"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.EXPERTISE"
                            }
                        ],
                        "current_gold": 498,
                        "current_hp": 61,
                        "damage_taken": 3,
                        "gold_gained": 336,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.STRENGTH_POTION",
                                "was_picked": true
                            }
                        ],
                        "potion_used": [
                            "POTION.POWER_POTION"
                        ],
                        "relic_choices": [
                            {
                                "choice": "RELIC.OLD_COIN",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.PHROG_PARASITE_ELITE",
                        "monster_ids": [
                            "MONSTER.PHROG_PARASITE"
                        ],
                        "room_type": "elite",
                        "turns_taken": 5
                    }
                ]
            },
            {
                "map_point_type": "shop",
                "player_stats": [
                    {
                        "bought_colorless": [
                            "CARD.PROLONG"
                        ],
                        "bought_relics": [
                            "RELIC.CANDELABRA"
                        ],
                        "card_choices": [
                            {
                                "card": {
                                    "id": "CARD.SLICE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.FLECHETTES"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.DEFLECT"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.BLADE_DANCE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.WELL_LAID_PLANS"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.MAYHEM"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.PROLONG"
                            }
                        ],
                        "cards_removed": [
                            {
                                "floor_added_to_deck": 1,
                                "id": "CARD.STRIKE_SILENT"
                            }
                        ],
                        "current_gold": 87,
                        "current_hp": 61,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 411,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.RADIANT_TINCTURE",
                                "was_picked": false
                            },
                            {
                                "choice": "POTION.FRUIT_JUICE",
                                "was_picked": false
                            },
                            {
                                "choice": "POTION.SWIFT_POTION",
                                "was_picked": false
                            }
                        ],
                        "relic_choices": [
                            {
                                "choice": "RELIC.CANDELABRA",
                                "was_picked": true
                            },
                            {
                                "choice": "RELIC.VENERABLE_TEA_SET",
                                "was_picked": false
                            },
                            {
                                "choice": "RELIC.MYSTIC_LIGHTER",
                                "was_picked": false
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "shop",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 8,
                                    "id": "CARD.ESCAPE_PLAN"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.DEFLECT"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.FLECHETTES"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.ESCAPE_PLAN"
                            }
                        ],
                        "current_gold": 99,
                        "current_hp": 58,
                        "damage_taken": 3,
                        "gold_gained": 12,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.SLITHERING_STRANGLER_NORMAL",
                        "monster_ids": [
                            "MONSTER.LEAF_SLIME_S",
                            "MONSTER.TWIG_SLIME_S",
                            "MONSTER.SLITHERING_STRANGLER"
                        ],
                        "room_type": "monster",
                        "turns_taken": 6
                    }
                ]
            },
            {
                "map_point_type": "rest_site",
                "player_stats": [
                    {
                        "current_gold": 99,
                        "current_hp": 58,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "rest_site_choices": [
                            "SMITH"
                        ],
                        "upgraded_cards": [
                            "CARD.PROLONG"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "rest_site",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "treasure",
                "player_stats": [
                    {
                        "current_gold": 99,
                        "current_hp": 58,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "room_type": "treasure",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "elite",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 11,
                                    "id": "CARD.THE_HUNT"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.DAGGER_THROW"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.FOOTWORK"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.THE_HUNT"
                            }
                        ],
                        "current_gold": 137,
                        "current_hp": 55,
                        "damage_taken": 3,
                        "gold_gained": 38,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.POWDERED_DEMISE",
                                "was_picked": true
                            }
                        ],
                        "relic_choices": [
                            {
                                "choice": "RELIC.REPTILE_TRINKET",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.BYRDONIS_ELITE",
                        "monster_ids": [
                            "MONSTER.BYRDONIS"
                        ],
                        "room_type": "elite",
                        "turns_taken": 5
                    }
                ]
            },
            {
                "map_point_type": "rest_site",
                "player_stats": [
                    {
                        "current_gold": 137,
                        "current_hp": 55,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "rest_site_choices": [
                            "SMITH"
                        ],
                        "upgraded_cards": [
                            "CARD.THE_HUNT"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "rest_site",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 13,
                                    "id": "CARD.PINPOINT"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.ACROBATICS"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.UNTOUCHABLE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "floor_added_to_deck": 13,
                                    "id": "CARD.BACKFLIP"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.FLICK_FLACK"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.DODGE_AND_ROLL"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.PINPOINT"
                            },
                            {
                                "id": "CARD.BACKFLIP"
                            }
                        ],
                        "current_gold": 155,
                        "current_hp": 55,
                        "damage_taken": 0,
                        "gold_gained": 18,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.MAWLER_NORMAL",
                        "monster_ids": [
                            "MONSTER.MAWLER"
                        ],
                        "room_type": "monster",
                        "turns_taken": 5
                    }
                ]
            },
            {
                "map_point_type": "elite",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 14,
                                    "id": "CARD.UNTOUCHABLE"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.EXPOSE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.DODGE_AND_ROLL"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.PREDATOR"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.PRECISE_CUT"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.SLICE"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.UNTOUCHABLE"
                            }
                        ],
                        "current_gold": 199,
                        "current_hp": 38,
                        "damage_taken": 17,
                        "gold_gained": 44,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_used": [
                            "POTION.STRENGTH_POTION"
                        ],
                        "relic_choices": [
                            {
                                "choice": "RELIC.ODDLY_SMOOTH_STONE",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.BYGONE_EFFIGY_ELITE",
                        "monster_ids": [
                            "MONSTER.BYGONE_EFFIGY"
                        ],
                        "room_type": "elite",
                        "turns_taken": 5
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 15,
                                    "id": "CARD.TACTICIAN"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.DAGGER_SPRAY"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.SHADOW_STEP"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "floor_added_to_deck": 15,
                                    "id": "CARD.ACROBATICS"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.UNTOUCHABLE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.MEMENTO_MORI"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.TACTICIAN"
                            },
                            {
                                "id": "CARD.ACROBATICS"
                            }
                        ],
                        "current_gold": 218,
                        "current_hp": 38,
                        "damage_taken": 0,
                        "gold_gained": 19,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.CLARITY",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.VINE_SHAMBLER_NORMAL",
                        "monster_ids": [
                            "MONSTER.VINE_SHAMBLER"
                        ],
                        "room_type": "monster",
                        "turns_taken": 3
                    }
                ]
            },
            {
                "map_point_type": "rest_site",
                "player_stats": [
                    {
                        "current_gold": 218,
                        "current_hp": 38,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "rest_site_choices": [
                            "SMITH"
                        ],
                        "upgraded_cards": [
                            "CARD.TACTICIAN"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "rest_site",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "boss",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 17,
                                    "id": "CARD.TOOLS_OF_THE_TRADE"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.ASSASSINATE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.NIGHTMARE"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.TOOLS_OF_THE_TRADE"
                            }
                        ],
                        "current_gold": 318,
                        "current_hp": 32,
                        "damage_taken": 6,
                        "gold_gained": 100,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_used": [
                            "POTION.POWDERED_DEMISE",
                            "POTION.CLARITY"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.THE_KIN_BOSS",
                        "monster_ids": [
                            "MONSTER.KIN_FOLLOWER",
                            "MONSTER.KIN_FOLLOWER",
                            "MONSTER.KIN_PRIEST"
                        ],
                        "room_type": "boss",
                        "turns_taken": 11
                    }
                ]
            }
        ],
        [
            {
                "map_point_type": "ancient",
                "player_stats": [
                    {
                        "ancient_choice": [
                            {
                                "TextKey": "YUMMY_COOKIE",
                                "title": {
                                    "key": "YUMMY_COOKIE.title",
                                    "table": "relics"
                                },
                                "was_chosen": false
                            },
                            {
                                "TextKey": "STORYBOOK",
                                "title": {
                                    "key": "STORYBOOK.title",
                                    "table": "relics"
                                },
                                "was_chosen": false
                            },
                            {
                                "TextKey": "PUMPKIN_CANDLE",
                                "title": {
                                    "key": "PUMPKIN_CANDLE.title",
                                    "table": "relics"
                                },
                                "was_chosen": true
                            }
                        ],
                        "current_gold": 318,
                        "current_hp": 70,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 38,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "relic_choices": [
                            {
                                "choice": "RELIC.PUMPKIN_CANDLE",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "EVENT.TEZCATARA",
                        "room_type": "event",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "floor_added_to_deck": 19,
                                    "id": "CARD.DEADLY_POISON"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.BLUR"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.BLADE_DANCE"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "current_upgrade_level": 1,
                                "floor_added_to_deck": 15,
                                "id": "CARD.TACTICIAN"
                            },
                            {
                                "current_upgrade_level": 1,
                                "id": "CARD.DEADLY_POISON"
                            }
                        ],
                        "cards_removed": [
                            {
                                "current_upgrade_level": 1,
                                "floor_added_to_deck": 15,
                                "id": "CARD.TACTICIAN"
                            }
                        ],
                        "current_gold": 336,
                        "current_hp": 68,
                        "damage_taken": 2,
                        "gold_gained": 18,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.DISTILLED_CHAOS",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.THIEVING_HOPPER_WEAK",
                        "monster_ids": [
                            "MONSTER.THIEVING_HOPPER"
                        ],
                        "room_type": "monster",
                        "turns_taken": 5
                    }
                ]
            },
            {
                "map_point_type": "shop",
                "player_stats": [
                    {
                        "bought_colorless": [
                            "CARD.THINKING_AHEAD"
                        ],
                        "bought_relics": [
                            "RELIC.MEMBERSHIP_CARD"
                        ],
                        "card_choices": [
                            {
                                "card": {
                                    "id": "CARD.LEADING_STRIKE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.SUCKER_PUNCH"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.ANTICIPATE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.DODGE_AND_ROLL"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.WELL_LAID_PLANS"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.REND"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.THINKING_AHEAD"
                            }
                        ],
                        "cards_removed": [
                            {
                                "floor_added_to_deck": 1,
                                "id": "CARD.STRIKE_SILENT"
                            }
                        ],
                        "current_gold": 2,
                        "current_hp": 68,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 334,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.FIRE_POTION",
                                "was_picked": false
                            },
                            {
                                "choice": "POTION.BLOCK_POTION",
                                "was_picked": false
                            },
                            {
                                "choice": "POTION.DUPLICATOR",
                                "was_picked": false
                            }
                        ],
                        "relic_choices": [
                            {
                                "choice": "RELIC.MEMBERSHIP_CARD",
                                "was_picked": true
                            },
                            {
                                "choice": "RELIC.UNCEASING_TOP",
                                "was_picked": false
                            },
                            {
                                "choice": "RELIC.RED_MASK",
                                "was_picked": false
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "shop",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "unknown",
                "player_stats": [
                    {
                        "current_gold": 65,
                        "current_hp": 62,
                        "damage_taken": 6,
                        "event_choices": [
                            {
                                "title": {
                                    "key": "THIS_OR_THAT.pages.INITIAL.options.PLAIN.title",
                                    "table": "events"
                                },
                                "variables": {
                                    "Curse": {
                                        "type": "DynamicString",
                                        "decimal_value": 0,
                                        "bool_value": false,
                                        "string_value": "Torpeza"
                                    }
                                }
                            }
                        ],
                        "gold_gained": 63,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "EVENT.THIS_OR_THAT",
                        "room_type": "event",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "unknown",
                "player_stats": [
                    {
                        "cards_gained": [
                            {
                                "id": "CARD.PREPARED"
                            }
                        ],
                        "current_gold": 65,
                        "current_hp": 62,
                        "damage_taken": 0,
                        "event_choices": [
                            {
                                "title": {
                                    "key": "BRAIN_LEECH.pages.INITIAL.options.SHARE_KNOWLEDGE.title",
                                    "table": "events"
                                }
                            }
                        ],
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "EVENT.BRAIN_LEECH",
                        "room_type": "event",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "rest_site",
                "player_stats": [
                    {
                        "current_gold": 65,
                        "current_hp": 62,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "rest_site_choices": [
                            "SMITH"
                        ],
                        "upgraded_cards": [
                            "CARD.THINKING_AHEAD"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "rest_site",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "shop",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "id": "CARD.FINISHER"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.SUCKER_PUNCH"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.SHADOW_STEP"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.BACKFLIP"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.INFINITE_BLADES"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.DRAMATIC_ENTRANCE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.MAYHEM"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_removed": [
                            {
                                "floor_added_to_deck": 1,
                                "id": "CARD.DEFEND_SILENT"
                            }
                        ],
                        "current_gold": 3,
                        "current_hp": 62,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 62,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.FIRE_POTION",
                                "was_picked": false
                            },
                            {
                                "choice": "POTION.FORTIFIER",
                                "was_picked": false
                            },
                            {
                                "choice": "POTION.SNECKO_OIL",
                                "was_picked": false
                            }
                        ],
                        "relic_choices": [
                            {
                                "choice": "RELIC.BOOK_OF_FIVE_RINGS",
                                "was_picked": false
                            },
                            {
                                "choice": "RELIC.HORN_CLEAT",
                                "was_picked": false
                            },
                            {
                                "choice": "RELIC.DINGY_RUG",
                                "was_picked": false
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "shop",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "elite",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 25,
                                    "id": "CARD.ANTICIPATE"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "id": "CARD.DEADLY_POISON"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.DAGGER_SPRAY"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.ANTICIPATE"
                            }
                        ],
                        "current_gold": 43,
                        "current_hp": 45,
                        "damage_taken": 17,
                        "gold_gained": 40,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.POTION_OF_BINDING",
                                "was_picked": true
                            }
                        ],
                        "relic_choices": [
                            {
                                "choice": "RELIC.PERMAFROST",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.INFESTED_PRISMS_ELITE",
                        "monster_ids": [
                            "MONSTER.INFESTED_PRISM"
                        ],
                        "room_type": "elite",
                        "turns_taken": 7
                    }
                ]
            },
            {
                "map_point_type": "treasure",
                "player_stats": [
                    {
                        "current_gold": 92,
                        "current_hp": 45,
                        "damage_taken": 0,
                        "gold_gained": 49,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "relic_choices": [
                            {
                                "choice": "RELIC.GORGET",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "treasure",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "elite",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "id": "CARD.DAGGER_SPRAY"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "id": "CARD.LEADING_STRIKE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.ENVENOM"
                                },
                                "was_picked": false
                            }
                        ],
                        "current_gold": 133,
                        "current_hp": 45,
                        "damage_taken": 0,
                        "gold_gained": 41,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "relic_choices": [
                            {
                                "choice": "RELIC.MERCURY_HOURGLASS",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.ENTOMANCER_ELITE",
                        "monster_ids": [
                            "MONSTER.ENTOMANCER"
                        ],
                        "room_type": "elite",
                        "turns_taken": 5
                    }
                ]
            },
            {
                "map_point_type": "rest_site",
                "player_stats": [
                    {
                        "current_gold": 133,
                        "current_hp": 66,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 21,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "rest_site_choices": [
                            "HEAL"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "rest_site",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 29,
                                    "id": "CARD.FLICK_FLACK"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.LEADING_STRIKE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.ACCURACY"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.SUCKER_PUNCH"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "id": "CARD.DAGGER_THROW"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.STRANGLE"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.FLICK_FLACK"
                            }
                        ],
                        "current_gold": 152,
                        "current_hp": 63,
                        "damage_taken": 3,
                        "gold_gained": 19,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.DUPLICATOR",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.EXOSKELETONS_WEAK",
                        "monster_ids": [
                            "MONSTER.EXOSKELETON",
                            "MONSTER.EXOSKELETON",
                            "MONSTER.EXOSKELETON"
                        ],
                        "room_type": "monster",
                        "turns_taken": 3
                    }
                ]
            },
            {
                "map_point_type": "unknown",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "floor_added_to_deck": 30,
                                    "id": "CARD.BACKFLIP"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "id": "CARD.BLADE_DANCE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.DEADLY_POISON"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.SUCKER_PUNCH"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.BLADE_DANCE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.PRECISE_CUT"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "current_upgrade_level": 1,
                                "id": "CARD.BACKFLIP"
                            }
                        ],
                        "current_gold": 163,
                        "current_hp": 63,
                        "damage_taken": 0,
                        "gold_gained": 11,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.SWIFT_POTION",
                                "was_picked": false
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.BOWLBUGS_NORMAL",
                        "monster_ids": [
                            "MONSTER.BOWLBUG_ROCK",
                            "MONSTER.BOWLBUG_EGG",
                            "MONSTER.BOWLBUG_NECTAR"
                        ],
                        "room_type": "monster",
                        "turns_taken": 3
                    }
                ]
            },
            {
                "map_point_type": "elite",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "floor_added_to_deck": 31,
                                    "id": "CARD.TOOLS_OF_THE_TRADE"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "id": "CARD.HAZE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "id": "CARD.PRECISE_CUT"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "floor_added_to_deck": 31,
                                    "id": "CARD.UNTOUCHABLE"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "id": "CARD.ANTICIPATE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.POISONED_STAB"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "id": "CARD.TOOLS_OF_THE_TRADE"
                            },
                            {
                                "id": "CARD.UNTOUCHABLE"
                            }
                        ],
                        "current_gold": 208,
                        "current_hp": 63,
                        "damage_taken": 0,
                        "gold_gained": 45,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.SWIFT_POTION",
                                "was_picked": true
                            }
                        ],
                        "potion_discarded": [
                            "POTION.POTION_OF_BINDING"
                        ],
                        "relic_choices": [
                            {
                                "choice": "RELIC.UNSETTLING_LAMP",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.DECIMILLIPEDE_ELITE",
                        "monster_ids": [
                            "MONSTER.DECIMILLIPEDE_SEGMENT_FRONT",
                            "MONSTER.DECIMILLIPEDE_SEGMENT_MIDDLE",
                            "MONSTER.DECIMILLIPEDE_SEGMENT_BACK"
                        ],
                        "room_type": "elite",
                        "turns_taken": 4
                    }
                ]
            },
            {
                "map_point_type": "rest_site",
                "player_stats": [
                    {
                        "current_gold": 208,
                        "current_hp": 63,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "rest_site_choices": [
                            "SMITH"
                        ],
                        "upgraded_cards": [
                            "CARD.TOOLS_OF_THE_TRADE"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "rest_site",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "boss",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "id": "CARD.FAN_OF_KNIVES"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.STORM_OF_STEEL"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.ECHOING_SLASH"
                                },
                                "was_picked": false
                            }
                        ],
                        "current_gold": 308,
                        "current_hp": 57,
                        "damage_taken": 6,
                        "gold_gained": 100,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.KNOWLEDGE_DEMON_BOSS",
                        "monster_ids": [
                            "MONSTER.KNOWLEDGE_DEMON"
                        ],
                        "room_type": "boss",
                        "turns_taken": 11
                    }
                ]
            }
        ],
        [
            {
                "map_point_type": "ancient",
                "player_stats": [
                    {
                        "ancient_choice": [
                            {
                                "TextKey": "JEWELRY_BOX",
                                "title": {
                                    "key": "JEWELRY_BOX.title",
                                    "table": "relics"
                                },
                                "was_chosen": false
                            },
                            {
                                "TextKey": "LOOMING_FRUIT",
                                "title": {
                                    "key": "LOOMING_FRUIT.title",
                                    "table": "relics"
                                },
                                "was_chosen": false
                            },
                            {
                                "TextKey": "GLITTER",
                                "title": {
                                    "key": "GLITTER.title",
                                    "table": "relics"
                                },
                                "was_chosen": true
                            }
                        ],
                        "current_gold": 308,
                        "current_hp": 70,
                        "damage_taken": 0,
                        "event_choices": [
                            {
                                "title": {
                                    "key": "GLITTER.title",
                                    "table": "relics"
                                }
                            }
                        ],
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 13,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "relic_choices": [
                            {
                                "choice": "RELIC.GLITTER",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "EVENT.NONUPEIPE",
                        "room_type": "event",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "enchantment": {
                                        "amount": 1,
                                        "id": "ENCHANTMENT.GLAM"
                                    },
                                    "floor_added_to_deck": 35,
                                    "id": "CARD.FLICK_FLACK"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "enchantment": {
                                        "amount": 1,
                                        "id": "ENCHANTMENT.GLAM"
                                    },
                                    "id": "CARD.PIERCING_WAIL"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "enchantment": {
                                        "amount": 1,
                                        "id": "ENCHANTMENT.GLAM"
                                    },
                                    "id": "CARD.ACCURACY"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "enchantment": {
                                        "amount": 1,
                                        "id": "ENCHANTMENT.GLAM"
                                    },
                                    "id": "CARD.STRANGLE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "enchantment": {
                                        "amount": 1,
                                        "id": "ENCHANTMENT.GLAM"
                                    },
                                    "id": "CARD.PIERCING_WAIL"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "enchantment": {
                                        "amount": 1,
                                        "id": "ENCHANTMENT.GLAM"
                                    },
                                    "id": "CARD.DODGE_AND_ROLL"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "enchantment": {
                                    "amount": 1,
                                    "id": "ENCHANTMENT.GLAM"
                                },
                                "id": "CARD.FLICK_FLACK"
                            }
                        ],
                        "current_gold": 326,
                        "current_hp": 70,
                        "damage_taken": 0,
                        "gold_gained": 18,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.TURRET_OPERATOR_WEAK",
                        "monster_ids": [
                            "MONSTER.LIVING_SHIELD",
                            "MONSTER.TURRET_OPERATOR"
                        ],
                        "room_type": "monster",
                        "turns_taken": 4
                    }
                ]
            },
            {
                "map_point_type": "unknown",
                "player_stats": [
                    {
                        "cards_removed": [
                            {
                                "floor_added_to_deck": 29,
                                "id": "CARD.FLICK_FLACK"
                            }
                        ],
                        "current_gold": 326,
                        "current_hp": 70,
                        "damage_taken": 0,
                        "event_choices": [
                            {
                                "title": {
                                    "key": "SLIPPERY_BRIDGE.pages.INITIAL.options.OVERCOME.title",
                                    "table": "events"
                                },
                                "variables": {
                                    "RandomCard": {
                                        "type": "DynamicString",
                                        "decimal_value": 0,
                                        "bool_value": false,
                                        "string_value": "Salto mortal"
                                    },
                                    "HpLoss": {
                                        "type": "BaseDynamic",
                                        "decimal_value": 3,
                                        "bool_value": false,
                                        "string_value": null
                                    }
                                }
                            }
                        ],
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "EVENT.SLIPPERY_BRIDGE",
                        "room_type": "event",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "enchantment": {
                                        "amount": 1,
                                        "id": "ENCHANTMENT.GLAM"
                                    },
                                    "id": "CARD.DEADLY_POISON"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "enchantment": {
                                        "amount": 1,
                                        "id": "ENCHANTMENT.GLAM"
                                    },
                                    "id": "CARD.POISONED_STAB"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "enchantment": {
                                        "amount": 1,
                                        "id": "ENCHANTMENT.GLAM"
                                    },
                                    "id": "CARD.DASH"
                                },
                                "was_picked": false
                            }
                        ],
                        "current_gold": 340,
                        "current_hp": 70,
                        "damage_taken": 0,
                        "gold_gained": 14,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.BLOCK_POTION",
                                "was_picked": false
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.DEVOTED_SCULPTOR_WEAK",
                        "monster_ids": [
                            "MONSTER.DEVOTED_SCULPTOR"
                        ],
                        "room_type": "monster",
                        "turns_taken": 5
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "enchantment": {
                                        "amount": 1,
                                        "id": "ENCHANTMENT.GLAM"
                                    },
                                    "floor_added_to_deck": 38,
                                    "id": "CARD.ACROBATICS"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "enchantment": {
                                        "amount": 1,
                                        "id": "ENCHANTMENT.GLAM"
                                    },
                                    "id": "CARD.BACKSTAB"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "enchantment": {
                                        "amount": 1,
                                        "id": "ENCHANTMENT.GLAM"
                                    },
                                    "id": "CARD.PRECISE_CUT"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "current_upgrade_level": 1,
                                "enchantment": {
                                    "amount": 1,
                                    "id": "ENCHANTMENT.GLAM"
                                },
                                "id": "CARD.ACROBATICS"
                            }
                        ],
                        "current_gold": 352,
                        "current_hp": 55,
                        "damage_taken": 15,
                        "gold_gained": 12,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.BLOCK_POTION",
                                "was_picked": false
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.GLOBE_HEAD_NORMAL",
                        "monster_ids": [
                            "MONSTER.GLOBE_HEAD"
                        ],
                        "room_type": "monster",
                        "turns_taken": 6
                    }
                ]
            },
            {
                "map_point_type": "rest_site",
                "player_stats": [
                    {
                        "current_gold": 352,
                        "current_hp": 55,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "rest_site_choices": [
                            "SMITH"
                        ],
                        "upgraded_cards": [
                            "CARD.PREPARED"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "rest_site",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "elite",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "enchantment": {
                                        "amount": 1,
                                        "id": "ENCHANTMENT.GLAM"
                                    },
                                    "floor_added_to_deck": 40,
                                    "id": "CARD.TACTICIAN"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "enchantment": {
                                        "amount": 1,
                                        "id": "ENCHANTMENT.GLAM"
                                    },
                                    "id": "CARD.DEADLY_POISON"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "enchantment": {
                                        "amount": 1,
                                        "id": "ENCHANTMENT.GLAM"
                                    },
                                    "id": "CARD.PREPARED"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "current_upgrade_level": 1,
                                "enchantment": {
                                    "amount": 1,
                                    "id": "ENCHANTMENT.GLAM"
                                },
                                "id": "CARD.TACTICIAN"
                            }
                        ],
                        "current_gold": 389,
                        "current_hp": 40,
                        "damage_taken": 15,
                        "gold_gained": 37,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.SWIFT_POTION",
                                "was_picked": true
                            }
                        ],
                        "potion_used": [
                            "POTION.DISTILLED_CHAOS"
                        ],
                        "relic_choices": [
                            {
                                "choice": "RELIC.HAPPY_FLOWER",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.MECHA_KNIGHT_ELITE",
                        "monster_ids": [
                            "MONSTER.MECHA_KNIGHT"
                        ],
                        "room_type": "elite",
                        "turns_taken": 9
                    }
                ]
            },
            {
                "map_point_type": "treasure",
                "player_stats": [
                    {
                        "current_gold": 435,
                        "current_hp": 40,
                        "damage_taken": 0,
                        "gold_gained": 46,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "relic_choices": [
                            {
                                "choice": "RELIC.WHETSTONE",
                                "was_picked": true
                            }
                        ],
                        "upgraded_cards": [
                            "CARD.STRIKE_SILENT",
                            "CARD.FLICK_FLACK"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "treasure",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "enchantment": {
                                        "amount": 1,
                                        "id": "ENCHANTMENT.GLAM"
                                    },
                                    "floor_added_to_deck": 42,
                                    "id": "CARD.MEMENTO_MORI"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "enchantment": {
                                        "amount": 1,
                                        "id": "ENCHANTMENT.GLAM"
                                    },
                                    "id": "CARD.SHADOWMELD"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "enchantment": {
                                        "amount": 1,
                                        "id": "ENCHANTMENT.GLAM"
                                    },
                                    "id": "CARD.BLADE_DANCE"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "current_upgrade_level": 1,
                                "enchantment": {
                                    "amount": 1,
                                    "id": "ENCHANTMENT.GLAM"
                                },
                                "id": "CARD.MEMENTO_MORI"
                            }
                        ],
                        "current_gold": 449,
                        "current_hp": 40,
                        "damage_taken": 0,
                        "gold_gained": 14,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.FORTIFIER",
                                "was_picked": true
                            }
                        ],
                        "potion_discarded": [
                            "POTION.SWIFT_POTION"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.OWL_MAGISTRATE_NORMAL",
                        "monster_ids": [
                            "MONSTER.OWL_MAGISTRATE"
                        ],
                        "room_type": "monster",
                        "turns_taken": 6
                    }
                ]
            },
            {
                "map_point_type": "shop",
                "player_stats": [
                    {
                        "bought_relics": [
                            "RELIC.LANTERN",
                            "RELIC.BAG_OF_PREPARATION"
                        ],
                        "card_choices": [
                            {
                                "card": {
                                    "id": "CARD.PRECISE_CUT"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.FLECHETTES"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.UP_MY_SLEEVE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.HAZE"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.ACCURACY"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.PROLONG"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "id": "CARD.BOLAS"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_removed": [
                            {
                                "floor_added_to_deck": 1,
                                "id": "CARD.STRIKE_SILENT"
                            }
                        ],
                        "current_gold": 191,
                        "current_hp": 40,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 258,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_choices": [
                            {
                                "choice": "POTION.DUPLICATOR",
                                "was_picked": false
                            },
                            {
                                "choice": "POTION.POWDERED_DEMISE",
                                "was_picked": false
                            },
                            {
                                "choice": "POTION.FLEX_POTION",
                                "was_picked": false
                            }
                        ],
                        "relic_choices": [
                            {
                                "choice": "RELIC.LANTERN",
                                "was_picked": true
                            },
                            {
                                "choice": "RELIC.BAG_OF_PREPARATION",
                                "was_picked": true
                            },
                            {
                                "choice": "RELIC.TOOLBOX",
                                "was_picked": false
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "shop",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "unknown",
                "player_stats": [
                    {
                        "cards_transformed": [
                            {
                                "final_card": {
                                    "floor_added_to_deck": 44,
                                    "id": "CARD.LEADING_STRIKE"
                                },
                                "original_card": {
                                    "floor_added_to_deck": 1,
                                    "id": "CARD.STRIKE_SILENT"
                                }
                            }
                        ],
                        "current_gold": 191,
                        "current_hp": 40,
                        "damage_taken": 0,
                        "event_choices": [
                            {
                                "title": {
                                    "key": "SYMBIOTE.pages.INITIAL.options.KILL_WITH_FIRE.title",
                                    "table": "events"
                                },
                                "variables": {
                                    "Enchantment": {
                                        "type": "DynamicString",
                                        "decimal_value": 0,
                                        "bool_value": false,
                                        "string_value": "Corrupci\u00f3n"
                                    }
                                }
                            }
                        ],
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1
                    }
                ],
                "rooms": [
                    {
                        "model_id": "EVENT.SYMBIOTE",
                        "room_type": "event",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "elite",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "enchantment": {
                                        "amount": 1,
                                        "id": "ENCHANTMENT.GLAM"
                                    },
                                    "floor_added_to_deck": 45,
                                    "id": "CARD.TACTICIAN"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "enchantment": {
                                        "amount": 1,
                                        "id": "ENCHANTMENT.GLAM"
                                    },
                                    "id": "CARD.DASH"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "enchantment": {
                                        "amount": 1,
                                        "id": "ENCHANTMENT.GLAM"
                                    },
                                    "id": "CARD.DEFLECT"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "enchantment": {
                                    "amount": 1,
                                    "id": "ENCHANTMENT.GLAM"
                                },
                                "id": "CARD.TACTICIAN"
                            }
                        ],
                        "current_gold": 235,
                        "current_hp": 40,
                        "damage_taken": 0,
                        "gold_gained": 44,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "relic_choices": [
                            {
                                "choice": "RELIC.ORNAMENTAL_FAN",
                                "was_picked": true
                            }
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.KNIGHTS_ELITE",
                        "monster_ids": [
                            "MONSTER.FLAIL_KNIGHT",
                            "MONSTER.SPECTRAL_KNIGHT",
                            "MONSTER.MAGI_KNIGHT"
                        ],
                        "room_type": "elite",
                        "turns_taken": 3
                    }
                ]
            },
            {
                "map_point_type": "monster",
                "player_stats": [
                    {
                        "card_choices": [
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "enchantment": {
                                        "amount": 1,
                                        "id": "ENCHANTMENT.GLAM"
                                    },
                                    "floor_added_to_deck": 46,
                                    "id": "CARD.TACTICIAN"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "enchantment": {
                                        "amount": 1,
                                        "id": "ENCHANTMENT.GLAM"
                                    },
                                    "id": "CARD.DASH"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "enchantment": {
                                        "amount": 1,
                                        "id": "ENCHANTMENT.GLAM"
                                    },
                                    "id": "CARD.DODGE_AND_ROLL"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "enchantment": {
                                        "amount": 1,
                                        "id": "ENCHANTMENT.GLAM"
                                    },
                                    "floor_added_to_deck": 46,
                                    "id": "CARD.CALCULATED_GAMBLE"
                                },
                                "was_picked": true
                            },
                            {
                                "card": {
                                    "enchantment": {
                                        "amount": 1,
                                        "id": "ENCHANTMENT.GLAM"
                                    },
                                    "id": "CARD.STORM_OF_STEEL"
                                },
                                "was_picked": false
                            },
                            {
                                "card": {
                                    "current_upgrade_level": 1,
                                    "enchantment": {
                                        "amount": 1,
                                        "id": "ENCHANTMENT.GLAM"
                                    },
                                    "id": "CARD.DODGE_AND_ROLL"
                                },
                                "was_picked": false
                            }
                        ],
                        "cards_gained": [
                            {
                                "current_upgrade_level": 1,
                                "enchantment": {
                                    "amount": 1,
                                    "id": "ENCHANTMENT.GLAM"
                                },
                                "id": "CARD.TACTICIAN"
                            },
                            {
                                "current_upgrade_level": 1,
                                "enchantment": {
                                    "amount": 1,
                                    "id": "ENCHANTMENT.GLAM"
                                },
                                "id": "CARD.CALCULATED_GAMBLE"
                            }
                        ],
                        "current_gold": 254,
                        "current_hp": 40,
                        "damage_taken": 0,
                        "gold_gained": 19,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_used": [
                            "POTION.SWIFT_POTION"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.SCROLLS_OF_BITING_NORMAL",
                        "monster_ids": [
                            "MONSTER.SCROLL_OF_BITING",
                            "MONSTER.SCROLL_OF_BITING",
                            "MONSTER.SCROLL_OF_BITING",
                            "MONSTER.SCROLL_OF_BITING"
                        ],
                        "room_type": "monster",
                        "turns_taken": 1
                    }
                ]
            },
            {
                "map_point_type": "rest_site",
                "player_stats": [
                    {
                        "current_gold": 254,
                        "current_hp": 40,
                        "damage_taken": 0,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "rest_site_choices": [
                            "SMITH"
                        ],
                        "upgraded_cards": [
                            "CARD.ACROBATICS"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "room_type": "rest_site",
                        "turns_taken": 0
                    }
                ]
            },
            {
                "map_point_type": "boss",
                "player_stats": [
                    {
                        "current_gold": 254,
                        "current_hp": 22,
                        "damage_taken": 18,
                        "gold_gained": 0,
                        "gold_lost": 0,
                        "gold_spent": 0,
                        "gold_stolen": 0,
                        "hp_healed": 0,
                        "max_hp": 70,
                        "max_hp_gained": 0,
                        "max_hp_lost": 0,
                        "player_id": 1,
                        "potion_used": [
                            "POTION.FORTIFIER",
                            "POTION.DUPLICATOR"
                        ]
                    }
                ],
                "rooms": [
                    {
                        "model_id": "ENCOUNTER.DOORMAKER_BOSS",
                        "monster_ids": [
                            "MONSTER.DOOR"
                        ],
                        "room_type": "boss",
                        "turns_taken": 17
                    }
                ]
            }
        ]
    ],
    "modifiers": [],
    "platform_type": "steam",
    "players": [
        {
            "character": "CHARACTER.SILENT",
            "deck": [
                {
                    "current_upgrade_level": 1,
                    "floor_added_to_deck": 1,
                    "id": "CARD.STRIKE_SILENT"
                },
                {
                    "floor_added_to_deck": 1,
                    "id": "CARD.DEFEND_SILENT"
                },
                {
                    "floor_added_to_deck": 1,
                    "id": "CARD.DEFEND_SILENT"
                },
                {
                    "floor_added_to_deck": 1,
                    "id": "CARD.DEFEND_SILENT"
                },
                {
                    "floor_added_to_deck": 1,
                    "id": "CARD.DEFEND_SILENT"
                },
                {
                    "floor_added_to_deck": 1,
                    "id": "CARD.NEUTRALIZE"
                },
                {
                    "floor_added_to_deck": 1,
                    "id": "CARD.SURVIVOR"
                },
                {
                    "current_upgrade_level": 1,
                    "floor_added_to_deck": 2,
                    "id": "CARD.BOUNCING_FLASK"
                },
                {
                    "current_upgrade_level": 1,
                    "floor_added_to_deck": 3,
                    "id": "CARD.DEFLECT"
                },
                {
                    "current_upgrade_level": 1,
                    "floor_added_to_deck": 4,
                    "id": "CARD.FLECHETTES"
                },
                {
                    "floor_added_to_deck": 6,
                    "id": "CARD.EXPERTISE"
                },
                {
                    "current_upgrade_level": 1,
                    "floor_added_to_deck": 7,
                    "id": "CARD.PROLONG"
                },
                {
                    "floor_added_to_deck": 8,
                    "id": "CARD.ESCAPE_PLAN"
                },
                {
                    "current_upgrade_level": 1,
                    "floor_added_to_deck": 11,
                    "id": "CARD.THE_HUNT"
                },
                {
                    "floor_added_to_deck": 13,
                    "id": "CARD.PINPOINT"
                },
                {
                    "floor_added_to_deck": 13,
                    "id": "CARD.BACKFLIP"
                },
                {
                    "floor_added_to_deck": 14,
                    "id": "CARD.UNTOUCHABLE"
                },
                {
                    "current_upgrade_level": 1,
                    "floor_added_to_deck": 15,
                    "id": "CARD.ACROBATICS"
                },
                {
                    "current_upgrade_level": 1,
                    "floor_added_to_deck": 17,
                    "id": "CARD.TOOLS_OF_THE_TRADE"
                },
                {
                    "current_upgrade_level": 1,
                    "floor_added_to_deck": 19,
                    "id": "CARD.TACTICIAN"
                },
                {
                    "current_upgrade_level": 1,
                    "floor_added_to_deck": 19,
                    "id": "CARD.DEADLY_POISON"
                },
                {
                    "current_upgrade_level": 1,
                    "floor_added_to_deck": 20,
                    "id": "CARD.THINKING_AHEAD"
                },
                {
                    "current_upgrade_level": 1,
                    "floor_added_to_deck": 22,
                    "id": "CARD.PREPARED"
                },
                {
                    "floor_added_to_deck": 25,
                    "id": "CARD.ANTICIPATE"
                },
                {
                    "current_upgrade_level": 1,
                    "floor_added_to_deck": 30,
                    "id": "CARD.BACKFLIP"
                },
                {
                    "floor_added_to_deck": 31,
                    "id": "CARD.TOOLS_OF_THE_TRADE"
                },
                {
                    "floor_added_to_deck": 31,
                    "id": "CARD.UNTOUCHABLE"
                },
                {
                    "current_upgrade_level": 1,
                    "enchantment": {
                        "amount": 1,
                        "id": "ENCHANTMENT.GLAM"
                    },
                    "floor_added_to_deck": 35,
                    "id": "CARD.FLICK_FLACK"
                },
                {
                    "current_upgrade_level": 1,
                    "enchantment": {
                        "amount": 1,
                        "id": "ENCHANTMENT.GLAM"
                    },
                    "floor_added_to_deck": 38,
                    "id": "CARD.ACROBATICS"
                },
                {
                    "current_upgrade_level": 1,
                    "enchantment": {
                        "amount": 1,
                        "id": "ENCHANTMENT.GLAM"
                    },
                    "floor_added_to_deck": 40,
                    "id": "CARD.TACTICIAN"
                },
                {
                    "current_upgrade_level": 1,
                    "enchantment": {
                        "amount": 1,
                        "id": "ENCHANTMENT.GLAM"
                    },
                    "floor_added_to_deck": 42,
                    "id": "CARD.MEMENTO_MORI"
                },
                {
                    "floor_added_to_deck": 44,
                    "id": "CARD.LEADING_STRIKE"
                },
                {
                    "enchantment": {
                        "amount": 1,
                        "id": "ENCHANTMENT.GLAM"
                    },
                    "floor_added_to_deck": 45,
                    "id": "CARD.TACTICIAN"
                },
                {
                    "current_upgrade_level": 1,
                    "enchantment": {
                        "amount": 1,
                        "id": "ENCHANTMENT.GLAM"
                    },
                    "floor_added_to_deck": 46,
                    "id": "CARD.TACTICIAN"
                },
                {
                    "current_upgrade_level": 1,
                    "enchantment": {
                        "amount": 1,
                        "id": "ENCHANTMENT.GLAM"
                    },
                    "floor_added_to_deck": 46,
                    "id": "CARD.CALCULATED_GAMBLE"
                }
            ],
            "id": 1,
            "max_potion_slot_count": 3,
            "potions": [],
            "relics": [
                {
                    "floor_added_to_deck": 1,
                    "id": "RELIC.RING_OF_THE_SNAKE"
                },
                {
                    "floor_added_to_deck": 1,
                    "id": "RELIC.SILVER_CRUCIBLE",
                    "props": {
                        "ints": [
                            {
                                "name": "TimesUsed",
                                "value": 3
                            },
                            {
                                "name": "TreasureRoomsEntered",
                                "value": 3
                            }
                        ]
                    }
                },
                {
                    "floor_added_to_deck": 6,
                    "id": "RELIC.OLD_COIN"
                },
                {
                    "floor_added_to_deck": 7,
                    "id": "RELIC.CANDELABRA"
                },
                {
                    "floor_added_to_deck": 11,
                    "id": "RELIC.REPTILE_TRINKET"
                },
                {
                    "floor_added_to_deck": 14,
                    "id": "RELIC.ODDLY_SMOOTH_STONE"
                },
                {
                    "floor_added_to_deck": 18,
                    "id": "RELIC.PUMPKIN_CANDLE",
                    "props": {
                        "ints": [
                            {
                                "name": "ActiveAct",
                                "value": 1
                            }
                        ]
                    }
                },
                {
                    "floor_added_to_deck": 20,
                    "id": "RELIC.MEMBERSHIP_CARD"
                },
                {
                    "floor_added_to_deck": 25,
                    "id": "RELIC.PERMAFROST"
                },
                {
                    "floor_added_to_deck": 26,
                    "id": "RELIC.GORGET"
                },
                {
                    "floor_added_to_deck": 27,
                    "id": "RELIC.MERCURY_HOURGLASS"
                },
                {
                    "floor_added_to_deck": 31,
                    "id": "RELIC.UNSETTLING_LAMP"
                },
                {
                    "floor_added_to_deck": 34,
                    "id": "RELIC.GLITTER"
                },
                {
                    "floor_added_to_deck": 40,
                    "id": "RELIC.HAPPY_FLOWER",
                    "props": {
                        "ints": [
                            {
                                "name": "TurnsSeen",
                                "value": 0
                            }
                        ]
                    }
                },
                {
                    "floor_added_to_deck": 41,
                    "id": "RELIC.WHETSTONE"
                },
                {
                    "floor_added_to_deck": 43,
                    "id": "RELIC.LANTERN"
                },
                {
                    "floor_added_to_deck": 43,
                    "id": "RELIC.BAG_OF_PREPARATION"
                },
                {
                    "floor_added_to_deck": 45,
                    "id": "RELIC.ORNAMENTAL_FAN"
                }
            ]
        }
    ],
    "run_time": 9784,
    "schema_version": 8,
    "seed": "ZTQ2FMMGKW",
    "start_time": 1773002695,
    "was_abandoned": false,
    "win": true
}